/* **********************************************************
 * Copyright 2019 VMware, Inc.  All rights reserved. -- VMware Confidential
 * **********************************************************/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	vmoperatorv1alpha1 "vmware.com/kubevsphere/pkg/apis/vmoperator/v1alpha1"
	clientset "vmware.com/kubevsphere/pkg/client/clientset_generated/clientset"
	internalinterfaces "vmware.com/kubevsphere/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "vmware.com/kubevsphere/pkg/client/listers_generated/vmoperator/v1alpha1"
)

// VirtualMachineServiceInformer provides access to a shared informer and lister for
// VirtualMachineServices.
type VirtualMachineServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VirtualMachineServiceLister
}

type virtualMachineServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVirtualMachineServiceInformer constructs a new informer for VirtualMachineService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualMachineServiceInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVirtualMachineServiceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVirtualMachineServiceInformer constructs a new informer for VirtualMachineService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualMachineServiceInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VmoperatorV1alpha1().VirtualMachineServices(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VmoperatorV1alpha1().VirtualMachineServices(namespace).Watch(options)
			},
		},
		&vmoperatorv1alpha1.VirtualMachineService{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualMachineServiceInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVirtualMachineServiceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *virtualMachineServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vmoperatorv1alpha1.VirtualMachineService{}, f.defaultInformer)
}

func (f *virtualMachineServiceInformer) Lister() v1alpha1.VirtualMachineServiceLister {
	return v1alpha1.NewVirtualMachineServiceLister(f.Informer().GetIndexer())
}
