/* **********************************************************
 * Copyright 2019 VMware, Inc.  All rights reserved. -- VMware Confidential
 * **********************************************************/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	vmoperatorv1alpha1 "github.com/vmware-tanzu/vm-operator/pkg/apis/vmoperator/v1alpha1"
	clientset "github.com/vmware-tanzu/vm-operator/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/vmware-tanzu/vm-operator/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/vmware-tanzu/vm-operator/pkg/client/listers_generated/vmoperator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VirtualMachineSetResourcePolicyInformer provides access to a shared informer and lister for
// VirtualMachineSetResourcePolicies.
type VirtualMachineSetResourcePolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VirtualMachineSetResourcePolicyLister
}

type virtualMachineSetResourcePolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVirtualMachineSetResourcePolicyInformer constructs a new informer for VirtualMachineSetResourcePolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualMachineSetResourcePolicyInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVirtualMachineSetResourcePolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVirtualMachineSetResourcePolicyInformer constructs a new informer for VirtualMachineSetResourcePolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualMachineSetResourcePolicyInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VmoperatorV1alpha1().VirtualMachineSetResourcePolicies(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VmoperatorV1alpha1().VirtualMachineSetResourcePolicies(namespace).Watch(options)
			},
		},
		&vmoperatorv1alpha1.VirtualMachineSetResourcePolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualMachineSetResourcePolicyInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVirtualMachineSetResourcePolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *virtualMachineSetResourcePolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vmoperatorv1alpha1.VirtualMachineSetResourcePolicy{}, f.defaultInformer)
}

func (f *virtualMachineSetResourcePolicyInformer) Lister() v1alpha1.VirtualMachineSetResourcePolicyLister {
	return v1alpha1.NewVirtualMachineSetResourcePolicyLister(f.Informer().GetIndexer())
}
