/* **********************************************************
 * Copyright 2019 VMware, Inc.  All rights reserved. -- VMware Confidential
 * **********************************************************/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"github.com/vmware-tanzu/vm-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/testing"
)

// FakeVirtualMachineSetResourcePolicies implements VirtualMachineSetResourcePolicyInterface
type FakeVirtualMachineSetResourcePolicies struct {
	Fake *FakeVmoperatorV1alpha1
	ns   string
}

var virtualmachinesetresourcepoliciesResource = schema.GroupVersionResource{Group: "vmoperator.vmware.com", Version: "v1alpha1", Resource: "virtualmachinesetresourcepolicies"}

var virtualmachinesetresourcepoliciesKind = schema.GroupVersionKind{Group: "vmoperator.vmware.com", Version: "v1alpha1", Kind: "VirtualMachineSetResourcePolicy"}

// Get takes name of the virtualMachineSetResourcePolicy, and returns the corresponding virtualMachineSetResourcePolicy object, and an error if there is any.
func (c *FakeVirtualMachineSetResourcePolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(virtualmachinesetresourcepoliciesResource, c.ns, name), &v1alpha1.VirtualMachineSetResourcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSetResourcePolicy), err
}

// List takes label and field selectors, and returns the list of VirtualMachineSetResourcePolicies that match those selectors.
func (c *FakeVirtualMachineSetResourcePolicies) List(opts v1.ListOptions) (result *v1alpha1.VirtualMachineSetResourcePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(virtualmachinesetresourcepoliciesResource, virtualmachinesetresourcepoliciesKind, c.ns, opts), &v1alpha1.VirtualMachineSetResourcePolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VirtualMachineSetResourcePolicyList{ListMeta: obj.(*v1alpha1.VirtualMachineSetResourcePolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.VirtualMachineSetResourcePolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualMachineSetResourcePolicies.
func (c *FakeVirtualMachineSetResourcePolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(virtualmachinesetresourcepoliciesResource, c.ns, opts))

}

// Create takes the representation of a virtualMachineSetResourcePolicy and creates it.  Returns the server's representation of the virtualMachineSetResourcePolicy, and an error, if there is any.
func (c *FakeVirtualMachineSetResourcePolicies) Create(virtualMachineSetResourcePolicy *v1alpha1.VirtualMachineSetResourcePolicy) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(virtualmachinesetresourcepoliciesResource, c.ns, virtualMachineSetResourcePolicy), &v1alpha1.VirtualMachineSetResourcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSetResourcePolicy), err
}

// Update takes the representation of a virtualMachineSetResourcePolicy and updates it. Returns the server's representation of the virtualMachineSetResourcePolicy, and an error, if there is any.
func (c *FakeVirtualMachineSetResourcePolicies) Update(virtualMachineSetResourcePolicy *v1alpha1.VirtualMachineSetResourcePolicy) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(virtualmachinesetresourcepoliciesResource, c.ns, virtualMachineSetResourcePolicy), &v1alpha1.VirtualMachineSetResourcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSetResourcePolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualMachineSetResourcePolicies) UpdateStatus(virtualMachineSetResourcePolicy *v1alpha1.VirtualMachineSetResourcePolicy) (*v1alpha1.VirtualMachineSetResourcePolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(virtualmachinesetresourcepoliciesResource, "status", c.ns, virtualMachineSetResourcePolicy), &v1alpha1.VirtualMachineSetResourcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSetResourcePolicy), err
}

// Delete takes name of the virtualMachineSetResourcePolicy and deletes it. Returns an error if one occurs.
func (c *FakeVirtualMachineSetResourcePolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(virtualmachinesetresourcepoliciesResource, c.ns, name), &v1alpha1.VirtualMachineSetResourcePolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualMachineSetResourcePolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(virtualmachinesetresourcepoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.VirtualMachineSetResourcePolicyList{})
	return err
}

// Patch applies the patch and returns the patched virtualMachineSetResourcePolicy.
func (c *FakeVirtualMachineSetResourcePolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtualmachinesetresourcepoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VirtualMachineSetResourcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSetResourcePolicy), err
}
