# This file contains the rules for golangci-lint
# It's a "copy" of https://opengrok.eng.vmware.com/source/xref/main.perforce.1666/bora/vpx/wcp/wcpsvc/src/server/.gometalinter.json
# with additional linters.

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 5m

  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-files:
   - ".*generated.*\\.go"

# override defaults
linters-settings:
  gocyclo:
    # minimal code complexity to report
    min-complexity: 18
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: gitlab.eng.vmware.com/core-build

# linters to enable in addition to the default linters
linters:
  enable:
    - dupl
    - gosec
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - interfacer
    - misspell
    - nakedret
    - scopelint
    #- stylecheck (too much existing code fails)
    - unconvert
    - unused
  disable-all: false
