site_name: VM Operator
site_url: https://github.com/vmware-tanzu/vm-operator
repo_url: https://github.com/vmware-tanzu/vm-operator
edit_uri: blob/main/docs/
docs_dir: docs
site_dir: .site

theme:
  name: material
  custom_dir: docs/www/themes/material

  favicon: favicon.svg
  icon:
    logo: vm-op/logo-white-solid

  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  features:
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - navigation.tabs
  - navigation.top
  - navigation.sections
  - navigation.expand
  - navigation.tracking
  - navigation.footer
  - navigation.header
  - navigation.path
  - navigation.indexes
  - toc.follow

extra_css:
- www/css/vm-operator.css
- www/css/vm-operator-font.css

plugins:
- search:
    separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
- markdownextradata:
    jinja_options:
      variable_start_string: "${{"
      variable_end_string: "}}"
# - git-committers:
#     enabled: !ENV [CI, false]
#     repository: vmware-tanzu/vm-operator
#     branch: main
# - git-revision-date-localized:
#     enabled: !ENV [CI, false]
#     enable_creation_date: true
# - optimize:
#     enabled: !ENV [CI, false]
# - minify:
#     minify_html: !ENV [CI, false]

extra:
  config:
    repo_url: https://github.com/vmware-tanzu/vm-operator
    repo_url_raw: https://raw.githubusercontent.com/vmware-tanzu/vm-operator
  # TODO(akutz) Get this working with RTFD
  # version:
  #   default: latest
  #   provider: mike

markdown_extensions:
- admonition
- pymdownx.snippets:
    check_paths: true
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
    options:
      custom_icons:
      - material/.icons
- pymdownx.inlinehilite
- pymdownx.highlight:
    use_pygments: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.details
- tables
- attr_list
- md_in_html

nav:
- Home: README.md
- Getting Started:
  - start/README.md
  - Quickstart: start/quick.md
  - Talk to Us: start/help.md
  - Contribute:
    - start/contrib/README.md
    - Suggest a Change: start/contrib/suggest-change.md
    - Report an Issue: start/contrib/report-issue.md
    - Submit a Change: start/contrib/submit-change.md
  - About:
    - start/about/README.md
    - Roadmap: start/about/roadmap.md
    - Release Notes: start/about/release-notes.md
    - License: start/about/license.md
- Concepts:
  - concepts/README.md
  # - Components: concepts/components.md
  # - API: concepts/api.md
  - Workloads:
    - concepts/workloads/README.md
    - VirtualMachine: concepts/workloads/vm.md
    - VirtualMachineClass: concepts/workloads/vm-class.md
    - WebConsoleRequest: concepts/workloads/vm-web-console.md
    - Guest Customization: concepts/workloads/guest.md
  - Images:
    - concepts/images/README.md
    - VirtualMachineImage: concepts/images/vm-image.md
    - Publish a VM Image: concepts/images/pub-vm-image.md
  - Services & Networking:
    - concepts/services-networking/README.md
    - VirtualMachineService: concepts/services-networking/vm-service.md
    - Guest Network Config: concepts/services-networking/guest-net-config.md
- Tutorials:
  - tutorials/README.md
  - Deploy VM:
    - tutorials/deploy-vm/README.md
    - With Cloud-Init: tutorials/deploy-vm/cloudinit.md
    - With vAppConfig: tutorials/deploy-vm/vappconfig.md
  - Troubleshooting:
    - tutorials/troubleshooting/README.md
    - Get a Console Session: tutorials/troubleshooting/get-console-session.md
    - VM Deployment: tutorials/troubleshooting/deploy-vm.md
    - IP Assignment: tutorials/troubleshooting/ip-assignment.md
    - VM Publish: tutorials/troubleshooting/publish-vm.md
- Reference:
  - ref/README.md
  - API:
    - ref/api/README.md
    - v1alpha1: ref/api/v1alpha1.md
    - v1alpha2: ref/api/v1alpha2.md
  - Configuration:
    - ref/config/README.md
    - Manager Pod: ref/config/manager.md
  - Project:
    - ref/proj/README.md
    - Build from Source: ref/proj/build.md
    - Create a Release: ref/proj/release.md
    - Writing Documentation: ref/proj/docs.md

