---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: WEBHOOK_CERTIFICATE_NAMESPACE_PLACEHOLDER/WEBHOOK_CERTIFICATE_NAME_PLACEHOLDER
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: WEBHOOK_CERTIFICATE_NAMESPACE_PLACEHOLDER/WEBHOOK_CERTIFICATE_NAME_PLACEHOLDER
