FROM node:20 AS build
WORKDIR /quicktype

COPY package.json package-lock.json* ./
RUN npm ci --prefix /quicktype quicktype

FROM gcr.io/distroless/nodejs20-debian12
COPY --from=build /quicktype /quicktype

WORKDIR /output
CMD [ \
    "/quicktype/node_modules/quicktype/dist/index.js", \
    "--src", "/schema-cloud-config-v1.json", \
    "--src-lang", "schema", \
    "--out", "/output/cloudconfig.go", \
    "--lang", "go", \
    "--package", "schema" \
]
