FROM node:20 AS build
WORKDIR /quicktype

RUN npm install --prefix /quicktype quicktype

FROM gcr.io/distroless/nodejs20-debian12
COPY --from=build /quicktype /quicktype

WORKDIR /output
CMD [ \
    "/quicktype/node_modules/quicktype/dist/index.js", \
    "--src", "/schema.json", \
    "--src-lang", "schema", \
    "--out", "/output/cloudconfig.go", \
    "--lang", "go", \
    "--package", "schema" \
]
