# Copyright (c) 2024-2023 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

TOOLS_DIR := ../../../../hack/tools
SCHEMA_IN := schema-cloud-config-v1.json
OUTPUT_GO := cloudconfig.go
QUICK_DIR := ../../../../hack/quicktype
START_TYP := Cloudconfig

include $(QUICK_DIR)/Makefile
