/* **********************************************************
 * Copyright 2018 VMware, Inc.  All rights reserved. -- VMware Confidential
 * **********************************************************/

// This file was automatically generated by informer-gen

package externalversions

import (
	"fmt"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
	v1beta1 "vmware.com/kubevsphere/pkg/apis/vmoperator/v1beta1"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=vmoperator.vmware.com, Version=v1beta1
	case v1beta1.SchemeGroupVersion.WithResource("virtualmachines"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Vmoperator().V1beta1().VirtualMachines().Informer()}, nil
	case v1beta1.SchemeGroupVersion.WithResource("virtualmachineimages"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Vmoperator().V1beta1().VirtualMachineImages().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
