# permissions to do view contentsourcebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contentsourcebinding-viewer-role
rules:
  - apiGroups:
      - vmoperator.vmware.com
    resources:
      - contentsourcebindings
    verbs:
      - get
      - list
      - watch
