# permissions to do viewer virtualmachineclassbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachineclassbinding-viewer-role
rules:
  - apiGroups:
      - vmoperator.vmware.com
    resources:
      - virtualmachineclassbindings
    verbs:
      - get
      - list
      - watch
