# permissions to do edit virtualmachineclassbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachineclassbinding-editor-role
rules:
  - apiGroups:
      - vmoperator.vmware.com
    resources:
      - virtualmachineclassbindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
