/* **********************************************************
 * Copyright 2018 VMware, Inc.  All rights reserved. -- VMware Confidential
 * **********************************************************/

// This file was automatically generated by informer-gen

package internalversion

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
	vmoperator "vmware.com/kubevsphere/pkg/apis/vmoperator"
	internalclientset "vmware.com/kubevsphere/pkg/client/clientset_generated/internalclientset"
	internalinterfaces "vmware.com/kubevsphere/pkg/client/informers_generated/internalversion/internalinterfaces"
	internalversion "vmware.com/kubevsphere/pkg/client/listers_generated/vmoperator/internalversion"
)

// VirtualMachineImageInformer provides access to a shared informer and lister for
// VirtualMachineImages.
type VirtualMachineImageInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.VirtualMachineImageLister
}

type virtualMachineImageInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVirtualMachineImageInformer constructs a new informer for VirtualMachineImage type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualMachineImageInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVirtualMachineImageInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVirtualMachineImageInformer constructs a new informer for VirtualMachineImage type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualMachineImageInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Vmoperator().VirtualMachineImages(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Vmoperator().VirtualMachineImages(namespace).Watch(options)
			},
		},
		&vmoperator.VirtualMachineImage{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualMachineImageInformer) defaultInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVirtualMachineImageInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *virtualMachineImageInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vmoperator.VirtualMachineImage{}, f.defaultInformer)
}

func (f *virtualMachineImageInformer) Lister() internalversion.VirtualMachineImageLister {
	return internalversion.NewVirtualMachineImageLister(f.Informer().GetIndexer())
}
