---
apiVersion: v1
kind: Service
metadata:
  name: conversion-webhook-service
  namespace: system
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    webhook: conversion
