// +build !ignore_autogenerated

/* **********************************************************
 * Copyright 2018 VMware, Inc.  All rights reserved. -- VMware Confidential
 * **********************************************************/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	vmoperator "vmware.com/kubevsphere/pkg/apis/vmoperator"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*VirtualMachine)(nil), (*vmoperator.VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachine_To_vmoperator_VirtualMachine(a.(*VirtualMachine), b.(*vmoperator.VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachine)(nil), (*VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachine_To_v1beta1_VirtualMachine(a.(*vmoperator.VirtualMachine), b.(*VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineCondition)(nil), (*vmoperator.VirtualMachineCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineCondition_To_vmoperator_VirtualMachineCondition(a.(*VirtualMachineCondition), b.(*vmoperator.VirtualMachineCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineCondition)(nil), (*VirtualMachineCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineCondition_To_v1beta1_VirtualMachineCondition(a.(*vmoperator.VirtualMachineCondition), b.(*VirtualMachineCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineImage)(nil), (*vmoperator.VirtualMachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineImage_To_vmoperator_VirtualMachineImage(a.(*VirtualMachineImage), b.(*vmoperator.VirtualMachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineImage)(nil), (*VirtualMachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineImage_To_v1beta1_VirtualMachineImage(a.(*vmoperator.VirtualMachineImage), b.(*VirtualMachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineImageList)(nil), (*vmoperator.VirtualMachineImageList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineImageList_To_vmoperator_VirtualMachineImageList(a.(*VirtualMachineImageList), b.(*vmoperator.VirtualMachineImageList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineImageList)(nil), (*VirtualMachineImageList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineImageList_To_v1beta1_VirtualMachineImageList(a.(*vmoperator.VirtualMachineImageList), b.(*VirtualMachineImageList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineImageSpec)(nil), (*vmoperator.VirtualMachineImageSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineImageSpec_To_vmoperator_VirtualMachineImageSpec(a.(*VirtualMachineImageSpec), b.(*vmoperator.VirtualMachineImageSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineImageSpec)(nil), (*VirtualMachineImageSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineImageSpec_To_v1beta1_VirtualMachineImageSpec(a.(*vmoperator.VirtualMachineImageSpec), b.(*VirtualMachineImageSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineImageStatus)(nil), (*vmoperator.VirtualMachineImageStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineImageStatus_To_vmoperator_VirtualMachineImageStatus(a.(*VirtualMachineImageStatus), b.(*vmoperator.VirtualMachineImageStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineImageStatus)(nil), (*VirtualMachineImageStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineImageStatus_To_v1beta1_VirtualMachineImageStatus(a.(*vmoperator.VirtualMachineImageStatus), b.(*VirtualMachineImageStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineImageStatusStrategy)(nil), (*vmoperator.VirtualMachineImageStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineImageStatusStrategy_To_vmoperator_VirtualMachineImageStatusStrategy(a.(*VirtualMachineImageStatusStrategy), b.(*vmoperator.VirtualMachineImageStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineImageStatusStrategy)(nil), (*VirtualMachineImageStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineImageStatusStrategy_To_v1beta1_VirtualMachineImageStatusStrategy(a.(*vmoperator.VirtualMachineImageStatusStrategy), b.(*VirtualMachineImageStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineImageStrategy)(nil), (*vmoperator.VirtualMachineImageStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineImageStrategy_To_vmoperator_VirtualMachineImageStrategy(a.(*VirtualMachineImageStrategy), b.(*vmoperator.VirtualMachineImageStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineImageStrategy)(nil), (*VirtualMachineImageStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineImageStrategy_To_v1beta1_VirtualMachineImageStrategy(a.(*vmoperator.VirtualMachineImageStrategy), b.(*VirtualMachineImageStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineList)(nil), (*vmoperator.VirtualMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineList_To_vmoperator_VirtualMachineList(a.(*VirtualMachineList), b.(*vmoperator.VirtualMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineList)(nil), (*VirtualMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineList_To_v1beta1_VirtualMachineList(a.(*vmoperator.VirtualMachineList), b.(*VirtualMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachinePort)(nil), (*vmoperator.VirtualMachinePort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachinePort_To_vmoperator_VirtualMachinePort(a.(*VirtualMachinePort), b.(*vmoperator.VirtualMachinePort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachinePort)(nil), (*VirtualMachinePort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachinePort_To_v1beta1_VirtualMachinePort(a.(*vmoperator.VirtualMachinePort), b.(*VirtualMachinePort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineResourceSpec)(nil), (*vmoperator.VirtualMachineResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineResourceSpec_To_vmoperator_VirtualMachineResourceSpec(a.(*VirtualMachineResourceSpec), b.(*vmoperator.VirtualMachineResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineResourceSpec)(nil), (*VirtualMachineResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineResourceSpec_To_v1beta1_VirtualMachineResourceSpec(a.(*vmoperator.VirtualMachineResourceSpec), b.(*VirtualMachineResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineResourcesSpec)(nil), (*vmoperator.VirtualMachineResourcesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineResourcesSpec_To_vmoperator_VirtualMachineResourcesSpec(a.(*VirtualMachineResourcesSpec), b.(*vmoperator.VirtualMachineResourcesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineResourcesSpec)(nil), (*VirtualMachineResourcesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineResourcesSpec_To_v1beta1_VirtualMachineResourcesSpec(a.(*vmoperator.VirtualMachineResourcesSpec), b.(*VirtualMachineResourcesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineService)(nil), (*vmoperator.VirtualMachineService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineService_To_vmoperator_VirtualMachineService(a.(*VirtualMachineService), b.(*vmoperator.VirtualMachineService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineService)(nil), (*VirtualMachineService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineService_To_v1beta1_VirtualMachineService(a.(*vmoperator.VirtualMachineService), b.(*VirtualMachineService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineServiceList)(nil), (*vmoperator.VirtualMachineServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineServiceList_To_vmoperator_VirtualMachineServiceList(a.(*VirtualMachineServiceList), b.(*vmoperator.VirtualMachineServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineServiceList)(nil), (*VirtualMachineServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineServiceList_To_v1beta1_VirtualMachineServiceList(a.(*vmoperator.VirtualMachineServiceList), b.(*VirtualMachineServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineServicePort)(nil), (*vmoperator.VirtualMachineServicePort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineServicePort_To_vmoperator_VirtualMachineServicePort(a.(*VirtualMachineServicePort), b.(*vmoperator.VirtualMachineServicePort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineServicePort)(nil), (*VirtualMachineServicePort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineServicePort_To_v1beta1_VirtualMachineServicePort(a.(*vmoperator.VirtualMachineServicePort), b.(*VirtualMachineServicePort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineServiceSpec)(nil), (*vmoperator.VirtualMachineServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineServiceSpec_To_vmoperator_VirtualMachineServiceSpec(a.(*VirtualMachineServiceSpec), b.(*vmoperator.VirtualMachineServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineServiceSpec)(nil), (*VirtualMachineServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineServiceSpec_To_v1beta1_VirtualMachineServiceSpec(a.(*vmoperator.VirtualMachineServiceSpec), b.(*VirtualMachineServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineServiceStatus)(nil), (*vmoperator.VirtualMachineServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineServiceStatus_To_vmoperator_VirtualMachineServiceStatus(a.(*VirtualMachineServiceStatus), b.(*vmoperator.VirtualMachineServiceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineServiceStatus)(nil), (*VirtualMachineServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineServiceStatus_To_v1beta1_VirtualMachineServiceStatus(a.(*vmoperator.VirtualMachineServiceStatus), b.(*VirtualMachineServiceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineServiceStatusStrategy)(nil), (*vmoperator.VirtualMachineServiceStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineServiceStatusStrategy_To_vmoperator_VirtualMachineServiceStatusStrategy(a.(*VirtualMachineServiceStatusStrategy), b.(*vmoperator.VirtualMachineServiceStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineServiceStatusStrategy)(nil), (*VirtualMachineServiceStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineServiceStatusStrategy_To_v1beta1_VirtualMachineServiceStatusStrategy(a.(*vmoperator.VirtualMachineServiceStatusStrategy), b.(*VirtualMachineServiceStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineServiceStrategy)(nil), (*vmoperator.VirtualMachineServiceStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineServiceStrategy_To_vmoperator_VirtualMachineServiceStrategy(a.(*VirtualMachineServiceStrategy), b.(*vmoperator.VirtualMachineServiceStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineServiceStrategy)(nil), (*VirtualMachineServiceStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineServiceStrategy_To_v1beta1_VirtualMachineServiceStrategy(a.(*vmoperator.VirtualMachineServiceStrategy), b.(*VirtualMachineServiceStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineSpec)(nil), (*vmoperator.VirtualMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineSpec_To_vmoperator_VirtualMachineSpec(a.(*VirtualMachineSpec), b.(*vmoperator.VirtualMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineSpec)(nil), (*VirtualMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineSpec_To_v1beta1_VirtualMachineSpec(a.(*vmoperator.VirtualMachineSpec), b.(*VirtualMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineStatus)(nil), (*vmoperator.VirtualMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineStatus_To_vmoperator_VirtualMachineStatus(a.(*VirtualMachineStatus), b.(*vmoperator.VirtualMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineStatus)(nil), (*VirtualMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineStatus_To_v1beta1_VirtualMachineStatus(a.(*vmoperator.VirtualMachineStatus), b.(*VirtualMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineStatusStrategy)(nil), (*vmoperator.VirtualMachineStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineStatusStrategy_To_vmoperator_VirtualMachineStatusStrategy(a.(*VirtualMachineStatusStrategy), b.(*vmoperator.VirtualMachineStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineStatusStrategy)(nil), (*VirtualMachineStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineStatusStrategy_To_v1beta1_VirtualMachineStatusStrategy(a.(*vmoperator.VirtualMachineStatusStrategy), b.(*VirtualMachineStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineStrategy)(nil), (*vmoperator.VirtualMachineStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineStrategy_To_vmoperator_VirtualMachineStrategy(a.(*VirtualMachineStrategy), b.(*vmoperator.VirtualMachineStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineStrategy)(nil), (*VirtualMachineStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineStrategy_To_v1beta1_VirtualMachineStrategy(a.(*vmoperator.VirtualMachineStrategy), b.(*VirtualMachineStrategy), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_VirtualMachine_To_vmoperator_VirtualMachine(in *VirtualMachine, out *vmoperator.VirtualMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_VirtualMachineSpec_To_vmoperator_VirtualMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_VirtualMachineStatus_To_vmoperator_VirtualMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_VirtualMachine_To_vmoperator_VirtualMachine is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachine_To_vmoperator_VirtualMachine(in *VirtualMachine, out *vmoperator.VirtualMachine, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachine_To_vmoperator_VirtualMachine(in, out, s)
}

func autoConvert_vmoperator_VirtualMachine_To_v1beta1_VirtualMachine(in *vmoperator.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_vmoperator_VirtualMachineSpec_To_v1beta1_VirtualMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_vmoperator_VirtualMachineStatus_To_v1beta1_VirtualMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_vmoperator_VirtualMachine_To_v1beta1_VirtualMachine is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachine_To_v1beta1_VirtualMachine(in *vmoperator.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachine_To_v1beta1_VirtualMachine(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineCondition_To_vmoperator_VirtualMachineCondition(in *VirtualMachineCondition, out *vmoperator.VirtualMachineCondition, s conversion.Scope) error {
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Message = in.Message
	out.Reason = in.Reason
	out.Status = in.Status
	out.Type = in.Type
	return nil
}

// Convert_v1beta1_VirtualMachineCondition_To_vmoperator_VirtualMachineCondition is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineCondition_To_vmoperator_VirtualMachineCondition(in *VirtualMachineCondition, out *vmoperator.VirtualMachineCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineCondition_To_vmoperator_VirtualMachineCondition(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineCondition_To_v1beta1_VirtualMachineCondition(in *vmoperator.VirtualMachineCondition, out *VirtualMachineCondition, s conversion.Scope) error {
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Message = in.Message
	out.Reason = in.Reason
	out.Status = in.Status
	out.Type = in.Type
	return nil
}

// Convert_vmoperator_VirtualMachineCondition_To_v1beta1_VirtualMachineCondition is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineCondition_To_v1beta1_VirtualMachineCondition(in *vmoperator.VirtualMachineCondition, out *VirtualMachineCondition, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineCondition_To_v1beta1_VirtualMachineCondition(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineImage_To_vmoperator_VirtualMachineImage(in *VirtualMachineImage, out *vmoperator.VirtualMachineImage, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_VirtualMachineImageSpec_To_vmoperator_VirtualMachineImageSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_VirtualMachineImageStatus_To_vmoperator_VirtualMachineImageStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_VirtualMachineImage_To_vmoperator_VirtualMachineImage is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineImage_To_vmoperator_VirtualMachineImage(in *VirtualMachineImage, out *vmoperator.VirtualMachineImage, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineImage_To_vmoperator_VirtualMachineImage(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineImage_To_v1beta1_VirtualMachineImage(in *vmoperator.VirtualMachineImage, out *VirtualMachineImage, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_vmoperator_VirtualMachineImageSpec_To_v1beta1_VirtualMachineImageSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_vmoperator_VirtualMachineImageStatus_To_v1beta1_VirtualMachineImageStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_vmoperator_VirtualMachineImage_To_v1beta1_VirtualMachineImage is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineImage_To_v1beta1_VirtualMachineImage(in *vmoperator.VirtualMachineImage, out *VirtualMachineImage, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineImage_To_v1beta1_VirtualMachineImage(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineImageList_To_vmoperator_VirtualMachineImageList(in *VirtualMachineImageList, out *vmoperator.VirtualMachineImageList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]vmoperator.VirtualMachineImage)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_VirtualMachineImageList_To_vmoperator_VirtualMachineImageList is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineImageList_To_vmoperator_VirtualMachineImageList(in *VirtualMachineImageList, out *vmoperator.VirtualMachineImageList, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineImageList_To_vmoperator_VirtualMachineImageList(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineImageList_To_v1beta1_VirtualMachineImageList(in *vmoperator.VirtualMachineImageList, out *VirtualMachineImageList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VirtualMachineImage)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_vmoperator_VirtualMachineImageList_To_v1beta1_VirtualMachineImageList is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineImageList_To_v1beta1_VirtualMachineImageList(in *vmoperator.VirtualMachineImageList, out *VirtualMachineImageList, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineImageList_To_v1beta1_VirtualMachineImageList(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineImageSpec_To_vmoperator_VirtualMachineImageSpec(in *VirtualMachineImageSpec, out *vmoperator.VirtualMachineImageSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_VirtualMachineImageSpec_To_vmoperator_VirtualMachineImageSpec is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineImageSpec_To_vmoperator_VirtualMachineImageSpec(in *VirtualMachineImageSpec, out *vmoperator.VirtualMachineImageSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineImageSpec_To_vmoperator_VirtualMachineImageSpec(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineImageSpec_To_v1beta1_VirtualMachineImageSpec(in *vmoperator.VirtualMachineImageSpec, out *VirtualMachineImageSpec, s conversion.Scope) error {
	return nil
}

// Convert_vmoperator_VirtualMachineImageSpec_To_v1beta1_VirtualMachineImageSpec is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineImageSpec_To_v1beta1_VirtualMachineImageSpec(in *vmoperator.VirtualMachineImageSpec, out *VirtualMachineImageSpec, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineImageSpec_To_v1beta1_VirtualMachineImageSpec(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineImageStatus_To_vmoperator_VirtualMachineImageStatus(in *VirtualMachineImageStatus, out *vmoperator.VirtualMachineImageStatus, s conversion.Scope) error {
	out.Uuid = in.Uuid
	out.InternalId = in.InternalId
	out.PowerState = in.PowerState
	return nil
}

// Convert_v1beta1_VirtualMachineImageStatus_To_vmoperator_VirtualMachineImageStatus is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineImageStatus_To_vmoperator_VirtualMachineImageStatus(in *VirtualMachineImageStatus, out *vmoperator.VirtualMachineImageStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineImageStatus_To_vmoperator_VirtualMachineImageStatus(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineImageStatus_To_v1beta1_VirtualMachineImageStatus(in *vmoperator.VirtualMachineImageStatus, out *VirtualMachineImageStatus, s conversion.Scope) error {
	out.Uuid = in.Uuid
	out.InternalId = in.InternalId
	out.PowerState = in.PowerState
	return nil
}

// Convert_vmoperator_VirtualMachineImageStatus_To_v1beta1_VirtualMachineImageStatus is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineImageStatus_To_v1beta1_VirtualMachineImageStatus(in *vmoperator.VirtualMachineImageStatus, out *VirtualMachineImageStatus, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineImageStatus_To_v1beta1_VirtualMachineImageStatus(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineImageStatusStrategy_To_vmoperator_VirtualMachineImageStatusStrategy(in *VirtualMachineImageStatusStrategy, out *vmoperator.VirtualMachineImageStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1beta1_VirtualMachineImageStatusStrategy_To_vmoperator_VirtualMachineImageStatusStrategy is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineImageStatusStrategy_To_vmoperator_VirtualMachineImageStatusStrategy(in *VirtualMachineImageStatusStrategy, out *vmoperator.VirtualMachineImageStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineImageStatusStrategy_To_vmoperator_VirtualMachineImageStatusStrategy(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineImageStatusStrategy_To_v1beta1_VirtualMachineImageStatusStrategy(in *vmoperator.VirtualMachineImageStatusStrategy, out *VirtualMachineImageStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_vmoperator_VirtualMachineImageStatusStrategy_To_v1beta1_VirtualMachineImageStatusStrategy is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineImageStatusStrategy_To_v1beta1_VirtualMachineImageStatusStrategy(in *vmoperator.VirtualMachineImageStatusStrategy, out *VirtualMachineImageStatusStrategy, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineImageStatusStrategy_To_v1beta1_VirtualMachineImageStatusStrategy(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineImageStrategy_To_vmoperator_VirtualMachineImageStrategy(in *VirtualMachineImageStrategy, out *vmoperator.VirtualMachineImageStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1beta1_VirtualMachineImageStrategy_To_vmoperator_VirtualMachineImageStrategy is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineImageStrategy_To_vmoperator_VirtualMachineImageStrategy(in *VirtualMachineImageStrategy, out *vmoperator.VirtualMachineImageStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineImageStrategy_To_vmoperator_VirtualMachineImageStrategy(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineImageStrategy_To_v1beta1_VirtualMachineImageStrategy(in *vmoperator.VirtualMachineImageStrategy, out *VirtualMachineImageStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_vmoperator_VirtualMachineImageStrategy_To_v1beta1_VirtualMachineImageStrategy is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineImageStrategy_To_v1beta1_VirtualMachineImageStrategy(in *vmoperator.VirtualMachineImageStrategy, out *VirtualMachineImageStrategy, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineImageStrategy_To_v1beta1_VirtualMachineImageStrategy(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineList_To_vmoperator_VirtualMachineList(in *VirtualMachineList, out *vmoperator.VirtualMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]vmoperator.VirtualMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_VirtualMachineList_To_vmoperator_VirtualMachineList is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineList_To_vmoperator_VirtualMachineList(in *VirtualMachineList, out *vmoperator.VirtualMachineList, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineList_To_vmoperator_VirtualMachineList(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineList_To_v1beta1_VirtualMachineList(in *vmoperator.VirtualMachineList, out *VirtualMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VirtualMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_vmoperator_VirtualMachineList_To_v1beta1_VirtualMachineList is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineList_To_v1beta1_VirtualMachineList(in *vmoperator.VirtualMachineList, out *VirtualMachineList, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineList_To_v1beta1_VirtualMachineList(in, out, s)
}

func autoConvert_v1beta1_VirtualMachinePort_To_vmoperator_VirtualMachinePort(in *VirtualMachinePort, out *vmoperator.VirtualMachinePort, s conversion.Scope) error {
	out.Port = in.Port
	out.Ip = in.Ip
	out.Name = in.Name
	out.Protocol = v1.Protocol(in.Protocol)
	return nil
}

// Convert_v1beta1_VirtualMachinePort_To_vmoperator_VirtualMachinePort is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachinePort_To_vmoperator_VirtualMachinePort(in *VirtualMachinePort, out *vmoperator.VirtualMachinePort, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachinePort_To_vmoperator_VirtualMachinePort(in, out, s)
}

func autoConvert_vmoperator_VirtualMachinePort_To_v1beta1_VirtualMachinePort(in *vmoperator.VirtualMachinePort, out *VirtualMachinePort, s conversion.Scope) error {
	out.Port = in.Port
	out.Ip = in.Ip
	out.Name = in.Name
	out.Protocol = v1.Protocol(in.Protocol)
	return nil
}

// Convert_vmoperator_VirtualMachinePort_To_v1beta1_VirtualMachinePort is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachinePort_To_v1beta1_VirtualMachinePort(in *vmoperator.VirtualMachinePort, out *VirtualMachinePort, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachinePort_To_v1beta1_VirtualMachinePort(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineResourceSpec_To_vmoperator_VirtualMachineResourceSpec(in *VirtualMachineResourceSpec, out *vmoperator.VirtualMachineResourceSpec, s conversion.Scope) error {
	out.Cpu = in.Cpu
	out.Memory = in.Memory
	return nil
}

// Convert_v1beta1_VirtualMachineResourceSpec_To_vmoperator_VirtualMachineResourceSpec is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineResourceSpec_To_vmoperator_VirtualMachineResourceSpec(in *VirtualMachineResourceSpec, out *vmoperator.VirtualMachineResourceSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineResourceSpec_To_vmoperator_VirtualMachineResourceSpec(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineResourceSpec_To_v1beta1_VirtualMachineResourceSpec(in *vmoperator.VirtualMachineResourceSpec, out *VirtualMachineResourceSpec, s conversion.Scope) error {
	out.Cpu = in.Cpu
	out.Memory = in.Memory
	return nil
}

// Convert_vmoperator_VirtualMachineResourceSpec_To_v1beta1_VirtualMachineResourceSpec is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineResourceSpec_To_v1beta1_VirtualMachineResourceSpec(in *vmoperator.VirtualMachineResourceSpec, out *VirtualMachineResourceSpec, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineResourceSpec_To_v1beta1_VirtualMachineResourceSpec(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineResourcesSpec_To_vmoperator_VirtualMachineResourcesSpec(in *VirtualMachineResourcesSpec, out *vmoperator.VirtualMachineResourcesSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_VirtualMachineResourceSpec_To_vmoperator_VirtualMachineResourceSpec(&in.Capacity, &out.Capacity, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_VirtualMachineResourceSpec_To_vmoperator_VirtualMachineResourceSpec(&in.Requests, &out.Requests, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_VirtualMachineResourceSpec_To_vmoperator_VirtualMachineResourceSpec(&in.Limits, &out.Limits, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_VirtualMachineResourcesSpec_To_vmoperator_VirtualMachineResourcesSpec is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineResourcesSpec_To_vmoperator_VirtualMachineResourcesSpec(in *VirtualMachineResourcesSpec, out *vmoperator.VirtualMachineResourcesSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineResourcesSpec_To_vmoperator_VirtualMachineResourcesSpec(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineResourcesSpec_To_v1beta1_VirtualMachineResourcesSpec(in *vmoperator.VirtualMachineResourcesSpec, out *VirtualMachineResourcesSpec, s conversion.Scope) error {
	if err := Convert_vmoperator_VirtualMachineResourceSpec_To_v1beta1_VirtualMachineResourceSpec(&in.Capacity, &out.Capacity, s); err != nil {
		return err
	}
	if err := Convert_vmoperator_VirtualMachineResourceSpec_To_v1beta1_VirtualMachineResourceSpec(&in.Requests, &out.Requests, s); err != nil {
		return err
	}
	if err := Convert_vmoperator_VirtualMachineResourceSpec_To_v1beta1_VirtualMachineResourceSpec(&in.Limits, &out.Limits, s); err != nil {
		return err
	}
	return nil
}

// Convert_vmoperator_VirtualMachineResourcesSpec_To_v1beta1_VirtualMachineResourcesSpec is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineResourcesSpec_To_v1beta1_VirtualMachineResourcesSpec(in *vmoperator.VirtualMachineResourcesSpec, out *VirtualMachineResourcesSpec, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineResourcesSpec_To_v1beta1_VirtualMachineResourcesSpec(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineService_To_vmoperator_VirtualMachineService(in *VirtualMachineService, out *vmoperator.VirtualMachineService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_VirtualMachineServiceSpec_To_vmoperator_VirtualMachineServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_VirtualMachineServiceStatus_To_vmoperator_VirtualMachineServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_VirtualMachineService_To_vmoperator_VirtualMachineService is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineService_To_vmoperator_VirtualMachineService(in *VirtualMachineService, out *vmoperator.VirtualMachineService, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineService_To_vmoperator_VirtualMachineService(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineService_To_v1beta1_VirtualMachineService(in *vmoperator.VirtualMachineService, out *VirtualMachineService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_vmoperator_VirtualMachineServiceSpec_To_v1beta1_VirtualMachineServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_vmoperator_VirtualMachineServiceStatus_To_v1beta1_VirtualMachineServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_vmoperator_VirtualMachineService_To_v1beta1_VirtualMachineService is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineService_To_v1beta1_VirtualMachineService(in *vmoperator.VirtualMachineService, out *VirtualMachineService, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineService_To_v1beta1_VirtualMachineService(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineServiceList_To_vmoperator_VirtualMachineServiceList(in *VirtualMachineServiceList, out *vmoperator.VirtualMachineServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]vmoperator.VirtualMachineService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_VirtualMachineServiceList_To_vmoperator_VirtualMachineServiceList is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineServiceList_To_vmoperator_VirtualMachineServiceList(in *VirtualMachineServiceList, out *vmoperator.VirtualMachineServiceList, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineServiceList_To_vmoperator_VirtualMachineServiceList(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineServiceList_To_v1beta1_VirtualMachineServiceList(in *vmoperator.VirtualMachineServiceList, out *VirtualMachineServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VirtualMachineService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_vmoperator_VirtualMachineServiceList_To_v1beta1_VirtualMachineServiceList is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineServiceList_To_v1beta1_VirtualMachineServiceList(in *vmoperator.VirtualMachineServiceList, out *VirtualMachineServiceList, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineServiceList_To_v1beta1_VirtualMachineServiceList(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineServicePort_To_vmoperator_VirtualMachineServicePort(in *VirtualMachineServicePort, out *vmoperator.VirtualMachineServicePort, s conversion.Scope) error {
	out.Name = in.Name
	out.Protocol = in.Protocol
	out.Port = in.Port
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_v1beta1_VirtualMachineServicePort_To_vmoperator_VirtualMachineServicePort is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineServicePort_To_vmoperator_VirtualMachineServicePort(in *VirtualMachineServicePort, out *vmoperator.VirtualMachineServicePort, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineServicePort_To_vmoperator_VirtualMachineServicePort(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineServicePort_To_v1beta1_VirtualMachineServicePort(in *vmoperator.VirtualMachineServicePort, out *VirtualMachineServicePort, s conversion.Scope) error {
	out.Name = in.Name
	out.Protocol = in.Protocol
	out.Port = in.Port
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_vmoperator_VirtualMachineServicePort_To_v1beta1_VirtualMachineServicePort is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineServicePort_To_v1beta1_VirtualMachineServicePort(in *vmoperator.VirtualMachineServicePort, out *VirtualMachineServicePort, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineServicePort_To_v1beta1_VirtualMachineServicePort(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineServiceSpec_To_vmoperator_VirtualMachineServiceSpec(in *VirtualMachineServiceSpec, out *vmoperator.VirtualMachineServiceSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.Ports = *(*[]vmoperator.VirtualMachineServicePort)(unsafe.Pointer(&in.Ports))
	out.Selector = *(*map[string]string)(unsafe.Pointer(&in.Selector))
	out.ClusterIP = in.ClusterIP
	out.ExternalName = in.ExternalName
	return nil
}

// Convert_v1beta1_VirtualMachineServiceSpec_To_vmoperator_VirtualMachineServiceSpec is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineServiceSpec_To_vmoperator_VirtualMachineServiceSpec(in *VirtualMachineServiceSpec, out *vmoperator.VirtualMachineServiceSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineServiceSpec_To_vmoperator_VirtualMachineServiceSpec(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineServiceSpec_To_v1beta1_VirtualMachineServiceSpec(in *vmoperator.VirtualMachineServiceSpec, out *VirtualMachineServiceSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.Ports = *(*[]VirtualMachineServicePort)(unsafe.Pointer(&in.Ports))
	out.Selector = *(*map[string]string)(unsafe.Pointer(&in.Selector))
	out.ClusterIP = in.ClusterIP
	out.ExternalName = in.ExternalName
	return nil
}

// Convert_vmoperator_VirtualMachineServiceSpec_To_v1beta1_VirtualMachineServiceSpec is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineServiceSpec_To_v1beta1_VirtualMachineServiceSpec(in *vmoperator.VirtualMachineServiceSpec, out *VirtualMachineServiceSpec, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineServiceSpec_To_v1beta1_VirtualMachineServiceSpec(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineServiceStatus_To_vmoperator_VirtualMachineServiceStatus(in *VirtualMachineServiceStatus, out *vmoperator.VirtualMachineServiceStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_VirtualMachineServiceStatus_To_vmoperator_VirtualMachineServiceStatus is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineServiceStatus_To_vmoperator_VirtualMachineServiceStatus(in *VirtualMachineServiceStatus, out *vmoperator.VirtualMachineServiceStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineServiceStatus_To_vmoperator_VirtualMachineServiceStatus(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineServiceStatus_To_v1beta1_VirtualMachineServiceStatus(in *vmoperator.VirtualMachineServiceStatus, out *VirtualMachineServiceStatus, s conversion.Scope) error {
	return nil
}

// Convert_vmoperator_VirtualMachineServiceStatus_To_v1beta1_VirtualMachineServiceStatus is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineServiceStatus_To_v1beta1_VirtualMachineServiceStatus(in *vmoperator.VirtualMachineServiceStatus, out *VirtualMachineServiceStatus, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineServiceStatus_To_v1beta1_VirtualMachineServiceStatus(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineServiceStatusStrategy_To_vmoperator_VirtualMachineServiceStatusStrategy(in *VirtualMachineServiceStatusStrategy, out *vmoperator.VirtualMachineServiceStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1beta1_VirtualMachineServiceStatusStrategy_To_vmoperator_VirtualMachineServiceStatusStrategy is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineServiceStatusStrategy_To_vmoperator_VirtualMachineServiceStatusStrategy(in *VirtualMachineServiceStatusStrategy, out *vmoperator.VirtualMachineServiceStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineServiceStatusStrategy_To_vmoperator_VirtualMachineServiceStatusStrategy(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineServiceStatusStrategy_To_v1beta1_VirtualMachineServiceStatusStrategy(in *vmoperator.VirtualMachineServiceStatusStrategy, out *VirtualMachineServiceStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_vmoperator_VirtualMachineServiceStatusStrategy_To_v1beta1_VirtualMachineServiceStatusStrategy is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineServiceStatusStrategy_To_v1beta1_VirtualMachineServiceStatusStrategy(in *vmoperator.VirtualMachineServiceStatusStrategy, out *VirtualMachineServiceStatusStrategy, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineServiceStatusStrategy_To_v1beta1_VirtualMachineServiceStatusStrategy(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineServiceStrategy_To_vmoperator_VirtualMachineServiceStrategy(in *VirtualMachineServiceStrategy, out *vmoperator.VirtualMachineServiceStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1beta1_VirtualMachineServiceStrategy_To_vmoperator_VirtualMachineServiceStrategy is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineServiceStrategy_To_vmoperator_VirtualMachineServiceStrategy(in *VirtualMachineServiceStrategy, out *vmoperator.VirtualMachineServiceStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineServiceStrategy_To_vmoperator_VirtualMachineServiceStrategy(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineServiceStrategy_To_v1beta1_VirtualMachineServiceStrategy(in *vmoperator.VirtualMachineServiceStrategy, out *VirtualMachineServiceStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_vmoperator_VirtualMachineServiceStrategy_To_v1beta1_VirtualMachineServiceStrategy is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineServiceStrategy_To_v1beta1_VirtualMachineServiceStrategy(in *vmoperator.VirtualMachineServiceStrategy, out *VirtualMachineServiceStrategy, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineServiceStrategy_To_v1beta1_VirtualMachineServiceStrategy(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineSpec_To_vmoperator_VirtualMachineSpec(in *VirtualMachineSpec, out *vmoperator.VirtualMachineSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_v1beta1_VirtualMachineResourcesSpec_To_vmoperator_VirtualMachineResourcesSpec(&in.Resources, &out.Resources, s); err != nil {
		return err
	}
	out.PowerState = in.PowerState
	out.Env = in.Env
	out.Ports = *(*[]vmoperator.VirtualMachinePort)(unsafe.Pointer(&in.Ports))
	return nil
}

// Convert_v1beta1_VirtualMachineSpec_To_vmoperator_VirtualMachineSpec is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineSpec_To_vmoperator_VirtualMachineSpec(in *VirtualMachineSpec, out *vmoperator.VirtualMachineSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineSpec_To_vmoperator_VirtualMachineSpec(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineSpec_To_v1beta1_VirtualMachineSpec(in *vmoperator.VirtualMachineSpec, out *VirtualMachineSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_vmoperator_VirtualMachineResourcesSpec_To_v1beta1_VirtualMachineResourcesSpec(&in.Resources, &out.Resources, s); err != nil {
		return err
	}
	out.PowerState = in.PowerState
	out.Env = in.Env
	out.Ports = *(*[]VirtualMachinePort)(unsafe.Pointer(&in.Ports))
	return nil
}

// Convert_vmoperator_VirtualMachineSpec_To_v1beta1_VirtualMachineSpec is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineSpec_To_v1beta1_VirtualMachineSpec(in *vmoperator.VirtualMachineSpec, out *VirtualMachineSpec, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineSpec_To_v1beta1_VirtualMachineSpec(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineStatus_To_vmoperator_VirtualMachineStatus(in *VirtualMachineStatus, out *vmoperator.VirtualMachineStatus, s conversion.Scope) error {
	out.Conditions = *(*[]vmoperator.VirtualMachineCondition)(unsafe.Pointer(&in.Conditions))
	out.Host = in.Host
	out.PowerState = in.PowerState
	out.Phase = in.Phase
	out.VmIp = in.VmIp
	return nil
}

// Convert_v1beta1_VirtualMachineStatus_To_vmoperator_VirtualMachineStatus is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineStatus_To_vmoperator_VirtualMachineStatus(in *VirtualMachineStatus, out *vmoperator.VirtualMachineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineStatus_To_vmoperator_VirtualMachineStatus(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineStatus_To_v1beta1_VirtualMachineStatus(in *vmoperator.VirtualMachineStatus, out *VirtualMachineStatus, s conversion.Scope) error {
	out.Conditions = *(*[]VirtualMachineCondition)(unsafe.Pointer(&in.Conditions))
	out.Host = in.Host
	out.PowerState = in.PowerState
	out.Phase = in.Phase
	out.VmIp = in.VmIp
	return nil
}

// Convert_vmoperator_VirtualMachineStatus_To_v1beta1_VirtualMachineStatus is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineStatus_To_v1beta1_VirtualMachineStatus(in *vmoperator.VirtualMachineStatus, out *VirtualMachineStatus, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineStatus_To_v1beta1_VirtualMachineStatus(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineStatusStrategy_To_vmoperator_VirtualMachineStatusStrategy(in *VirtualMachineStatusStrategy, out *vmoperator.VirtualMachineStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1beta1_VirtualMachineStatusStrategy_To_vmoperator_VirtualMachineStatusStrategy is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineStatusStrategy_To_vmoperator_VirtualMachineStatusStrategy(in *VirtualMachineStatusStrategy, out *vmoperator.VirtualMachineStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineStatusStrategy_To_vmoperator_VirtualMachineStatusStrategy(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineStatusStrategy_To_v1beta1_VirtualMachineStatusStrategy(in *vmoperator.VirtualMachineStatusStrategy, out *VirtualMachineStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_vmoperator_VirtualMachineStatusStrategy_To_v1beta1_VirtualMachineStatusStrategy is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineStatusStrategy_To_v1beta1_VirtualMachineStatusStrategy(in *vmoperator.VirtualMachineStatusStrategy, out *VirtualMachineStatusStrategy, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineStatusStrategy_To_v1beta1_VirtualMachineStatusStrategy(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineStrategy_To_vmoperator_VirtualMachineStrategy(in *VirtualMachineStrategy, out *vmoperator.VirtualMachineStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1beta1_VirtualMachineStrategy_To_vmoperator_VirtualMachineStrategy is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineStrategy_To_vmoperator_VirtualMachineStrategy(in *VirtualMachineStrategy, out *vmoperator.VirtualMachineStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineStrategy_To_vmoperator_VirtualMachineStrategy(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineStrategy_To_v1beta1_VirtualMachineStrategy(in *vmoperator.VirtualMachineStrategy, out *VirtualMachineStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_vmoperator_VirtualMachineStrategy_To_v1beta1_VirtualMachineStrategy is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineStrategy_To_v1beta1_VirtualMachineStrategy(in *vmoperator.VirtualMachineStrategy, out *VirtualMachineStrategy, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineStrategy_To_v1beta1_VirtualMachineStrategy(in, out, s)
}
