// © Broadcom. All Rights Reserved.
// The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: Apache-2.0

package vmopv1_test

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	vmopv1 "github.com/vmware-tanzu/vm-operator/api/v1alpha5"
	vmopv1util "github.com/vmware-tanzu/vm-operator/pkg/util/vmopv1"
)

var _ = Describe("IsControllerDiskSupported", func() {

	DescribeTable("supported combinations",
		func(
			controllerType vmopv1.VirtualControllerType,
			scsiControllerType vmopv1.SCSIControllerType,
			controllerSharing vmopv1.VirtualControllerSharingMode,
			diskMode vmopv1.VolumeDiskMode,
			diskSharing vmopv1.VolumeSharingMode,
			diskProvisioningType vmopv1util.DiskProvisioningType,
			guestID string,
		) {
			err := vmopv1util.IsControllerDiskSupported(
				controllerType,
				scsiControllerType,
				controllerSharing,
				diskMode,
				diskSharing,
				diskProvisioningType,
				guestID,
			)
			Expect(err).ToNot(HaveOccurred())
		},

		// ========================================================================
		// Comprehensive test coverage for all 123 supported combinations
		// Generated from empirical permutation test results
		// ========================================================================

		// BusLogic - supported combinations
		Entry("scsi-buslogic-none-persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("scsi-buslogic-none-persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("scsi-buslogic-none-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-buslogic-none-persistent-multi-writer-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-buslogic-none-independent_persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("scsi-buslogic-none-independent_persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("scsi-buslogic-none-independent_persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-buslogic-none-independent_nonpersistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("scsi-buslogic-none-independent_nonpersistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("scsi-buslogic-virtual-persistent-multi-writer-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-buslogic-physical-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModePhysical,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-buslogic-virtual-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		// LSI Logic - supported combinations
		Entry("scsi-lsilogic-none-persistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-none-persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-none-persistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-none-persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-none-persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-none-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-none-independent_persistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-none-independent_persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-none-independent_persistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-none-independent_persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-none-independent_nonpersistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-none-independent_nonpersistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-virtual-persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-virtual-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-physical-persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModePhysical,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-physical-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModePhysical,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-none-persistent-multi-writer-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-none-persistent-multi-writer-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-virtual-persistent-multi-writer-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		// LSI Logic SAS - supported combinations
		Entry("scsi-lsilogic-sas-none-persistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-sas-none-persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-sas-none-persistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-sas-none-persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-sas-none-persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-sas-none-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-sas-none-independent_persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-sas-virtual-persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-sas-virtual-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-lsilogic-sas-physical-persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModePhysical,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("scsi-lsilogic-sas-physical-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModePhysical,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),

		// PVSCSI - supported combinations
		Entry("scsi-pvscsi-none-persistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("scsi-pvscsi-none-persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("scsi-pvscsi-none-persistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("scsi-pvscsi-none-persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("scsi-pvscsi-none-persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("scsi-pvscsi-none-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-pvscsi-none-independent_persistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("scsi-pvscsi-none-independent_persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("scsi-pvscsi-none-independent_persistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("scsi-pvscsi-none-independent_persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("scsi-pvscsi-none-independent_persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-pvscsi-none-independent_nonpersistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("scsi-pvscsi-none-independent_nonpersistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("scsi-pvscsi-none-independent_nonpersistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("scsi-pvscsi-none-independent_nonpersistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("scsi-pvscsi-virtual-persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("scsi-pvscsi-virtual-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-pvscsi-physical-persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModePhysical,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("scsi-pvscsi-physical-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModePhysical,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-pvscsi-none-persistent-multi-writer-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("scsi-pvscsi-none-persistent-multi-writer-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-pvscsi-virtual-persistent-multi-writer-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("scsi-pvscsi-virtual-persistent-multi-writer-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("scsi-pvscsi-physical-persistent-multi-writer-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModePhysical,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),

		// IDE - supported combinations
		Entry("ide-ide-none-persistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("ide-ide-none-persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("ide-ide-none-persistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("ide-ide-none-persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("ide-ide-none-persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("ide-ide-none-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("ide-ide-none-independent_persistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("ide-ide-none-independent_persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("ide-ide-none-independent_persistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("ide-ide-none-independent_persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("ide-ide-none-independent_persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("ide-ide-none-independent_persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("ide-ide-none-independent_nonpersistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("ide-ide-none-independent_nonpersistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("ide-ide-none-independent_nonpersistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("ide-ide-none-independent_nonpersistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("ide-ide-none-independent_nonpersistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("ide-ide-none-independent_nonpersistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("ide-ide-none-persistent-multi-writer-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("ide-ide-none-persistent-multi-writer-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),

		// SATA - supported combinations
		Entry("sata-ahci-none-persistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("sata-ahci-none-persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("sata-ahci-none-persistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("sata-ahci-none-persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("sata-ahci-none-persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("sata-ahci-none-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("sata-ahci-none-independent_persistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("sata-ahci-none-independent_persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("sata-ahci-none-independent_persistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("sata-ahci-none-independent_persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("sata-ahci-none-independent_persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("sata-ahci-none-independent_persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("sata-ahci-none-independent_nonpersistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("sata-ahci-none-independent_nonpersistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("sata-ahci-none-independent_nonpersistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("sata-ahci-none-independent_nonpersistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("sata-ahci-none-independent_nonpersistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("sata-ahci-none-persistent-multi-writer-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("sata-ahci-none-persistent-multi-writer-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),

		// NVME - supported combinations
		Entry("nvme-nvme-none-persistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("nvme-nvme-none-persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("nvme-nvme-none-persistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("nvme-nvme-none-persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("nvme-nvme-none-persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("nvme-nvme-none-persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("nvme-nvme-none-independent_persistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("nvme-nvme-none-independent_persistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("nvme-nvme-none-independent_persistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("nvme-nvme-none-independent_persistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("nvme-nvme-none-independent_persistent-none-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("nvme-nvme-none-independent_persistent-none-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
		Entry("nvme-nvme-none-independent_nonpersistent-none-lazy-otherlinux64",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
		),
		Entry("nvme-nvme-none-independent_nonpersistent-none-lazy-otherguest",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
		),
		Entry("nvme-nvme-none-independent_nonpersistent-none-eager-otherlinux64",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinux64guest",
		),
		Entry("nvme-nvme-none-independent_nonpersistent-none-eager-otherguest",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThick,
			"otherlinuxguest",
		),
		Entry("nvme-nvme-none-persistent-multi-writer-eagerzero-otherlinux64",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
		),
		Entry("nvme-nvme-none-persistent-multi-writer-eagerzero-otherguest",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
		),
	)

	DescribeTable("unsupported combinations",
		func(
			controllerType vmopv1.VirtualControllerType,
			scsiControllerType vmopv1.SCSIControllerType,
			controllerSharing vmopv1.VirtualControllerSharingMode,
			diskMode vmopv1.VolumeDiskMode,
			diskSharing vmopv1.VolumeSharingMode,
			diskProvisioningType vmopv1util.DiskProvisioningType,
			guestID string,
			expectedError error,
		) {
			err := vmopv1util.IsControllerDiskSupported(
				controllerType,
				scsiControllerType,
				controllerSharing,
				diskMode,
				diskSharing,
				diskProvisioningType,
				guestID,
			)
			Expect(err).To(HaveOccurred())
			Expect(err).To(Equal(expectedError))
		},

		// BusLogic SCSI with otherlinux64guest - not supported for 64-bit guests
		Entry("BusLogic SCSI not supported for 64-bit guests",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
			vmopv1util.ErrBusLogicNot64BitGuest,
		),
		Entry("BusLogic SCSI with virtual sharing and multi-writer not supported for 64-bit guests",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinux64guest",
			vmopv1util.ErrBusLogicNot64BitGuest,
		),

		// Legacy disk modes - BusLogic
		Entry("BusLogic with nonpersistent disk mode not supported",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
			vmopv1util.ErrLegacyDiskModes,
		),

		// Virtual/Physical sharing with non-multi-writer requires thick provisioning - BusLogic
		Entry("BusLogic with virtual sharing and persistent non-multi-writer requires thick provisioning",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
			vmopv1util.ErrVirtualSharingPersistentThick,
		),
		Entry("BusLogic with physical sharing and independent persistent non-multi-writer requires thick provisioning",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeBusLogic,
			vmopv1.VirtualControllerSharingModePhysical,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
			vmopv1util.ErrPhysicalSharingIndependentPersistentThick,
		),

		// LSI Logic - legacy disk modes
		Entry("LSI Logic with nonpersistent disk mode not supported",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
			vmopv1util.ErrLegacyDiskModes,
		),

		// LSI Logic - sharing with non-multi-writer requires thick provisioning
		Entry("LSI Logic with virtual sharing and persistent non-multi-writer requires thick provisioning",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogic,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
			vmopv1util.ErrVirtualSharingPersistentThick,
		),

		// LSI Logic SAS - legacy disk modes
		Entry("LSI Logic SAS with nonpersistent disk mode not supported",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
			vmopv1util.ErrLegacyDiskModes,
		),

		// LSI Logic SAS - sharing with non-multi-writer requires thick provisioning
		Entry("LSI Logic SAS with virtual sharing and persistent non-multi-writer requires thick provisioning",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeLsiLogicSAS,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
			vmopv1util.ErrVirtualSharingPersistentThick,
		),

		// PVSCSI - legacy disk modes
		Entry("PVSCSI with nonpersistent disk mode not supported",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
			vmopv1util.ErrLegacyDiskModes,
		),

		// PVSCSI - sharing with non-multi-writer requires thick provisioning
		Entry("PVSCSI with virtual sharing and persistent non-multi-writer requires thick provisioning",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeVirtual,
			vmopv1.VolumeDiskModePersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
			vmopv1util.ErrVirtualSharingPersistentThick,
		),
		Entry("PVSCSI with physical sharing and independent nonpersistent non-multi-writer requires thick provisioning",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModePhysical,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
			vmopv1util.ErrPhysicalSharingIndependentNonPersistentThick,
		),

		// PVSCSI - multi-writer with independent_nonpersistent requires thick provisioning
		Entry("PVSCSI with independent nonpersistent multi-writer requires thick provisioning",
			vmopv1.VirtualControllerTypeSCSI,
			vmopv1.SCSIControllerTypeParaVirtualSCSI,
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
			vmopv1util.ErrMultiWriterIndependentNonPersistentThick,
		),

		// IDE - legacy disk modes
		Entry("IDE with nonpersistent disk mode not supported",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
			vmopv1util.ErrLegacyDiskModes,
		),

		// IDE - multi-writer with independent_nonpersistent requires thick provisioning
		Entry("IDE with independent nonpersistent multi-writer requires thick provisioning",
			vmopv1.VirtualControllerTypeIDE,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
			vmopv1util.ErrMultiWriterIndependentNonPersistentThick,
		),

		// SATA - legacy disk modes
		Entry("SATA with nonpersistent disk mode not supported",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
			vmopv1util.ErrLegacyDiskModes,
		),

		// SATA - multi-writer with independent_nonpersistent requires thick provisioning
		Entry("SATA with independent nonpersistent multi-writer requires thick provisioning",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinuxguest",
			vmopv1util.ErrMultiWriterIndependentNonPersistentThick,
		),

		// NVME - legacy disk modes
		Entry("NVME with nonpersistent disk mode not supported",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeNonPersistent,
			vmopv1.VolumeSharingModeNone,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
			vmopv1util.ErrLegacyDiskModes,
		),

		// NVME - multi-writer with independent_nonpersistent requires thick provisioning
		Entry("NVME with independent nonpersistent multi-writer requires thick provisioning",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentNonPersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThin,
			"otherlinux64guest",
			vmopv1util.ErrMultiWriterIndependentNonPersistentThick,
		),

		Entry("SATA, independent persistent, multi-writer, thickeagerzero, otherlinuxguest",
			vmopv1.VirtualControllerTypeSATA,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
			vmopv1util.ErrInvalidConfiguration,
		),

		Entry("NVME, independent persistent, multi-writer, thickeagerzero, otherlinuxguest",
			vmopv1.VirtualControllerTypeNVME,
			vmopv1.SCSIControllerType(""),
			vmopv1.VirtualControllerSharingModeNone,
			vmopv1.VolumeDiskModeIndependentPersistent,
			vmopv1.VolumeSharingModeMultiWriter,
			vmopv1util.DiskProvisioningTypeThickEagerZero,
			"otherlinuxguest",
			vmopv1util.ErrInvalidConfiguration,
		),
	)

	Context("guest ID normalization", func() {
		It("normalizes guest ID to lowercase", func() {
			// Test with uppercase variant
			err := vmopv1util.IsControllerDiskSupported(
				vmopv1.VirtualControllerTypeSCSI,
				vmopv1.SCSIControllerTypeParaVirtualSCSI,
				vmopv1.VirtualControllerSharingModeNone,
				vmopv1.VolumeDiskModePersistent,
				vmopv1.VolumeSharingModeNone,
				vmopv1util.DiskProvisioningTypeThin,
				"OTHERLINUX64GUEST",
			)
			Expect(err).ToNot(HaveOccurred())
		})

		It("defaults unknown guest IDs to otherlinux64guest", func() {
			// Test with unsupported configuration for otherlinux64guest
			err := vmopv1util.IsControllerDiskSupported(
				vmopv1.VirtualControllerTypeSCSI,
				vmopv1.SCSIControllerTypeBusLogic,
				vmopv1.VirtualControllerSharingModeNone,
				vmopv1.VolumeDiskModeIndependentNonPersistent,
				vmopv1.VolumeSharingModeNone,
				vmopv1util.DiskProvisioningTypeThin,
				"unknownGuestID",
			)
			// Should fail because unknown guest ID defaults to otherlinux64guest
			// and BusLogic is not supported for 64-bit guests
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("BusLogic SCSI adapter is not supported for 64-bit guests"))
		})
	})

	Context("controller type conversion", func() {
		It("handles all SCSI controller types", func() {
			scsiTypes := []vmopv1.SCSIControllerType{
				vmopv1.SCSIControllerTypeParaVirtualSCSI,
				vmopv1.SCSIControllerTypeLsiLogic,
				vmopv1.SCSIControllerTypeLsiLogicSAS,
				vmopv1.SCSIControllerTypeBusLogic,
			}

			for _, scsiType := range scsiTypes {
				err := vmopv1util.IsControllerDiskSupported(
					vmopv1.VirtualControllerTypeSCSI,
					scsiType,
					vmopv1.VirtualControllerSharingModeNone,
					vmopv1.VolumeDiskModePersistent,
					vmopv1.VolumeSharingModeNone,
					vmopv1util.DiskProvisioningTypeThin,
					"otherlinuxguest",
				)
				// All should succeed with this combination except BusLogic (which doesn't fail for otherlinuxguest with persistent)
				if scsiType == vmopv1.SCSIControllerTypeBusLogic {
					// BusLogic should succeed with otherlinuxguest and persistent mode
					Expect(err).ToNot(HaveOccurred(), "Failed for SCSI type: %s", scsiType)
				} else {
					Expect(err).ToNot(HaveOccurred(), "Failed for SCSI type: %s", scsiType)
				}
			}
		})

		It("handles all controller types", func() {
			controllerTypes := []vmopv1.VirtualControllerType{
				vmopv1.VirtualControllerTypeSCSI,
				vmopv1.VirtualControllerTypeIDE,
				vmopv1.VirtualControllerTypeSATA,
				vmopv1.VirtualControllerTypeNVME,
			}

			for _, ctrlType := range controllerTypes {
				scsiType := vmopv1.SCSIControllerType("")
				if ctrlType == vmopv1.VirtualControllerTypeSCSI {
					scsiType = vmopv1.SCSIControllerTypeParaVirtualSCSI
				}

				err := vmopv1util.IsControllerDiskSupported(
					ctrlType,
					scsiType,
					vmopv1.VirtualControllerSharingModeNone,
					vmopv1.VolumeDiskModePersistent,
					vmopv1.VolumeSharingModeNone,
					vmopv1util.DiskProvisioningTypeThin,
					"otherlinuxguest",
				)
				// All should succeed with this combination
				Expect(err).ToNot(HaveOccurred(), "Failed for controller type: %s", ctrlType)
			}
		})
	})

	Context("controller sharing modes", func() {
		It("handles all sharing modes for SCSI controllers", func() {
			sharingModes := []vmopv1.VirtualControllerSharingMode{
				vmopv1.VirtualControllerSharingModeNone,
				vmopv1.VirtualControllerSharingModeVirtual,
				vmopv1.VirtualControllerSharingModePhysical,
			}

			for _, sharingMode := range sharingModes {
				err := vmopv1util.IsControllerDiskSupported(
					vmopv1.VirtualControllerTypeSCSI,
					vmopv1.SCSIControllerTypeParaVirtualSCSI,
					sharingMode,
					vmopv1.VolumeDiskModePersistent,
					vmopv1.VolumeSharingModeMultiWriter,
					vmopv1util.DiskProvisioningTypeThickEagerZero,
					"otherlinuxguest",
				)
				// All should succeed with multi-writer
				Expect(err).ToNot(HaveOccurred(), "Failed for sharing mode: %s", sharingMode)
			}
		})
	})

	Context("disk modes", func() {
		It("handles all supported disk modes", func() {
			diskModes := []vmopv1.VolumeDiskMode{
				vmopv1.VolumeDiskModePersistent,
				vmopv1.VolumeDiskModeIndependentPersistent,
				vmopv1.VolumeDiskModeIndependentNonPersistent,
			}

			for _, diskMode := range diskModes {
				err := vmopv1util.IsControllerDiskSupported(
					vmopv1.VirtualControllerTypeIDE,
					"",
					vmopv1.VirtualControllerSharingModeNone,
					diskMode,
					vmopv1.VolumeSharingModeNone,
					vmopv1util.DiskProvisioningTypeThin,
					"otherlinuxguest",
				)
				// All should succeed with IDE and none sharing
				Expect(err).ToNot(HaveOccurred(), "Failed for disk mode: %s", diskMode)
			}
		})

		It("handles legacy disk mode as unsupported", func() {
			err := vmopv1util.IsControllerDiskSupported(
				vmopv1.VirtualControllerTypeIDE,
				"",
				vmopv1.VirtualControllerSharingModeNone,
				vmopv1.VolumeDiskModeNonPersistent,
				vmopv1.VolumeSharingModeNone,
				vmopv1util.DiskProvisioningTypeThin,
				"otherlinuxguest",
			)
			Expect(err).To(HaveOccurred())
			Expect(err).To(Equal(vmopv1util.ErrLegacyDiskModes))
		})
	})

	Context("volume sharing modes", func() {
		It("handles both volume sharing modes", func() {
			sharingModes := []vmopv1.VolumeSharingMode{
				vmopv1.VolumeSharingModeNone,
				vmopv1.VolumeSharingModeMultiWriter,
			}

			for _, sharingMode := range sharingModes {
				provisioningType := vmopv1util.DiskProvisioningTypeThin
				if sharingMode == vmopv1.VolumeSharingModeMultiWriter {
					provisioningType = vmopv1util.DiskProvisioningTypeThickEagerZero
				}
				err := vmopv1util.IsControllerDiskSupported(
					vmopv1.VirtualControllerTypeSCSI,
					vmopv1.SCSIControllerTypeParaVirtualSCSI,
					vmopv1.VirtualControllerSharingModeNone,
					vmopv1.VolumeDiskModePersistent,
					sharingMode,
					provisioningType,
					"otherlinuxguest",
				)
				Expect(err).ToNot(HaveOccurred(), "Failed for volume sharing mode: %s", sharingMode)
			}
		})
	})

	Context("default case coverage", func() {
		It("handles unknown controller type", func() {
			// Using an empty/unknown controller type should default to "unknown"
			err := vmopv1util.IsControllerDiskSupported(
				vmopv1.VirtualControllerType("UnknownController"),
				vmopv1.SCSIControllerType(""),
				vmopv1.VirtualControllerSharingModeNone,
				vmopv1.VolumeDiskModePersistent,
				vmopv1.VolumeSharingModeNone,
				vmopv1util.DiskProvisioningTypeThin,
				"otherlinuxguest",
			)
			// Should succeed since it's not in unsupported list
			Expect(err).ToNot(HaveOccurred())
		})

		It("handles unknown SCSI controller type", func() {
			// Using an empty/unknown SCSI type should default to pvscsi
			err := vmopv1util.IsControllerDiskSupported(
				vmopv1.VirtualControllerTypeSCSI,
				vmopv1.SCSIControllerType("UnknownSCSI"),
				vmopv1.VirtualControllerSharingModeNone,
				vmopv1.VolumeDiskModePersistent,
				vmopv1.VolumeSharingModeNone,
				vmopv1util.DiskProvisioningTypeThin,
				"otherlinuxguest",
			)
			// Should succeed since it defaults to pvscsi
			Expect(err).ToNot(HaveOccurred())
		})

		It("handles unknown controller sharing mode", func() {
			// Using an unknown sharing mode should default to "none"
			err := vmopv1util.IsControllerDiskSupported(
				vmopv1.VirtualControllerTypeSCSI,
				vmopv1.SCSIControllerTypeParaVirtualSCSI,
				vmopv1.VirtualControllerSharingMode("UnknownSharing"),
				vmopv1.VolumeDiskModePersistent,
				vmopv1.VolumeSharingModeNone,
				vmopv1util.DiskProvisioningTypeThin,
				"otherlinuxguest",
			)
			// Should succeed since it defaults to none
			Expect(err).ToNot(HaveOccurred())
		})

		It("handles unknown disk mode", func() {
			// Using an unknown disk mode should default to "persistent"
			err := vmopv1util.IsControllerDiskSupported(
				vmopv1.VirtualControllerTypeSCSI,
				vmopv1.SCSIControllerTypeParaVirtualSCSI,
				vmopv1.VirtualControllerSharingModeNone,
				vmopv1.VolumeDiskMode("UnknownDiskMode"),
				vmopv1.VolumeSharingModeNone,
				vmopv1util.DiskProvisioningTypeThin,
				"otherlinuxguest",
			)
			// Should succeed since it defaults to persistent
			Expect(err).ToNot(HaveOccurred())
		})

		It("handles unknown volume sharing mode", func() {
			// Using an unknown volume sharing mode should default to "none"
			err := vmopv1util.IsControllerDiskSupported(
				vmopv1.VirtualControllerTypeSCSI,
				vmopv1.SCSIControllerTypeParaVirtualSCSI,
				vmopv1.VirtualControllerSharingModeNone,
				vmopv1.VolumeDiskModePersistent,
				vmopv1.VolumeSharingMode("UnknownVolumeSharing"),
				vmopv1util.DiskProvisioningTypeThin,
				"otherlinuxguest",
			)
			// Should succeed since it defaults to none
			Expect(err).ToNot(HaveOccurred())
		})
	})
})
