// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/vmprovider/providers/vsphere/vmprovider.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	library "github.com/vmware/govmomi/vapi/library"
	vsphere "github.com/vmware-tanzu/vm-operator/pkg/vmprovider/providers/vsphere"
	resources "github.com/vmware-tanzu/vm-operator/pkg/vmprovider/providers/vsphere/resources"
)

// MockOvfPropertyRetriever is a mock of OvfPropertyRetriever interface
type MockOvfPropertyRetriever struct {
	ctrl     *gomock.Controller
	recorder *MockOvfPropertyRetrieverMockRecorder
}

// MockOvfPropertyRetrieverMockRecorder is the mock recorder for MockOvfPropertyRetriever
type MockOvfPropertyRetrieverMockRecorder struct {
	mock *MockOvfPropertyRetriever
}

// NewMockOvfPropertyRetriever creates a new mock instance
func NewMockOvfPropertyRetriever(ctrl *gomock.Controller) *MockOvfPropertyRetriever {
	mock := &MockOvfPropertyRetriever{ctrl: ctrl}
	mock.recorder = &MockOvfPropertyRetrieverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOvfPropertyRetriever) EXPECT() *MockOvfPropertyRetrieverMockRecorder {
	return m.recorder
}

// FetchOvfPropertiesFromLibrary mocks base method
func (m *MockOvfPropertyRetriever) FetchOvfPropertiesFromLibrary(ctx context.Context, sess *vsphere.Session, item *library.Item) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOvfPropertiesFromLibrary", ctx, sess, item)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOvfPropertiesFromLibrary indicates an expected call of FetchOvfPropertiesFromLibrary
func (mr *MockOvfPropertyRetrieverMockRecorder) FetchOvfPropertiesFromLibrary(ctx, sess, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOvfPropertiesFromLibrary", reflect.TypeOf((*MockOvfPropertyRetriever)(nil).FetchOvfPropertiesFromLibrary), ctx, sess, item)
}

// FetchOvfPropertiesFromVM mocks base method
func (m *MockOvfPropertyRetriever) FetchOvfPropertiesFromVM(ctx context.Context, resVm *resources.VirtualMachine) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOvfPropertiesFromVM", ctx, resVm)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOvfPropertiesFromVM indicates an expected call of FetchOvfPropertiesFromVM
func (mr *MockOvfPropertyRetrieverMockRecorder) FetchOvfPropertiesFromVM(ctx, resVm interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOvfPropertiesFromVM", reflect.TypeOf((*MockOvfPropertyRetriever)(nil).FetchOvfPropertiesFromVM), ctx, resVm)
}
