/* **********************************************************
 * Copyright 2018 VMware, Inc.  All rights reserved. -- VMware Confidential
 * **********************************************************/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// VirtualMachineListerExpansion allows custom methods to be added to
// VirtualMachineLister.
type VirtualMachineListerExpansion interface{}

// VirtualMachineNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineNamespaceLister.
type VirtualMachineNamespaceListerExpansion interface{}

// VirtualMachineImageListerExpansion allows custom methods to be added to
// VirtualMachineImageLister.
type VirtualMachineImageListerExpansion interface{}

// VirtualMachineImageNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineImageNamespaceLister.
type VirtualMachineImageNamespaceListerExpansion interface{}
