// +build !ignore_autogenerated

/* **********************************************************
 * Copyright 2019 VMware, Inc.  All rights reserved. -- VMware Confidential
 * **********************************************************/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	vmoperator "github.com/vmware-tanzu/vm-operator/pkg/apis/vmoperator"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*VirtualMachine)(nil), (*vmoperator.VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachine_To_vmoperator_VirtualMachine(a.(*VirtualMachine), b.(*vmoperator.VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachine)(nil), (*VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachine_To_v1alpha1_VirtualMachine(a.(*vmoperator.VirtualMachine), b.(*VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineClass)(nil), (*vmoperator.VirtualMachineClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineClass_To_vmoperator_VirtualMachineClass(a.(*VirtualMachineClass), b.(*vmoperator.VirtualMachineClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineClass)(nil), (*VirtualMachineClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineClass_To_v1alpha1_VirtualMachineClass(a.(*vmoperator.VirtualMachineClass), b.(*VirtualMachineClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineClassHardware)(nil), (*vmoperator.VirtualMachineClassHardware)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineClassHardware_To_vmoperator_VirtualMachineClassHardware(a.(*VirtualMachineClassHardware), b.(*vmoperator.VirtualMachineClassHardware), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineClassHardware)(nil), (*VirtualMachineClassHardware)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineClassHardware_To_v1alpha1_VirtualMachineClassHardware(a.(*vmoperator.VirtualMachineClassHardware), b.(*VirtualMachineClassHardware), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineClassList)(nil), (*vmoperator.VirtualMachineClassList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineClassList_To_vmoperator_VirtualMachineClassList(a.(*VirtualMachineClassList), b.(*vmoperator.VirtualMachineClassList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineClassList)(nil), (*VirtualMachineClassList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineClassList_To_v1alpha1_VirtualMachineClassList(a.(*vmoperator.VirtualMachineClassList), b.(*VirtualMachineClassList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineClassPolicies)(nil), (*vmoperator.VirtualMachineClassPolicies)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineClassPolicies_To_vmoperator_VirtualMachineClassPolicies(a.(*VirtualMachineClassPolicies), b.(*vmoperator.VirtualMachineClassPolicies), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineClassPolicies)(nil), (*VirtualMachineClassPolicies)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineClassPolicies_To_v1alpha1_VirtualMachineClassPolicies(a.(*vmoperator.VirtualMachineClassPolicies), b.(*VirtualMachineClassPolicies), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineClassResourceSpec)(nil), (*vmoperator.VirtualMachineClassResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineClassResourceSpec_To_vmoperator_VirtualMachineClassResourceSpec(a.(*VirtualMachineClassResourceSpec), b.(*vmoperator.VirtualMachineClassResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineClassResourceSpec)(nil), (*VirtualMachineClassResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineClassResourceSpec_To_v1alpha1_VirtualMachineClassResourceSpec(a.(*vmoperator.VirtualMachineClassResourceSpec), b.(*VirtualMachineClassResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineClassResources)(nil), (*vmoperator.VirtualMachineClassResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineClassResources_To_vmoperator_VirtualMachineClassResources(a.(*VirtualMachineClassResources), b.(*vmoperator.VirtualMachineClassResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineClassResources)(nil), (*VirtualMachineClassResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineClassResources_To_v1alpha1_VirtualMachineClassResources(a.(*vmoperator.VirtualMachineClassResources), b.(*VirtualMachineClassResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineClassSpec)(nil), (*vmoperator.VirtualMachineClassSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineClassSpec_To_vmoperator_VirtualMachineClassSpec(a.(*VirtualMachineClassSpec), b.(*vmoperator.VirtualMachineClassSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineClassSpec)(nil), (*VirtualMachineClassSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineClassSpec_To_v1alpha1_VirtualMachineClassSpec(a.(*vmoperator.VirtualMachineClassSpec), b.(*VirtualMachineClassSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineClassStatus)(nil), (*vmoperator.VirtualMachineClassStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineClassStatus_To_vmoperator_VirtualMachineClassStatus(a.(*VirtualMachineClassStatus), b.(*vmoperator.VirtualMachineClassStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineClassStatus)(nil), (*VirtualMachineClassStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineClassStatus_To_v1alpha1_VirtualMachineClassStatus(a.(*vmoperator.VirtualMachineClassStatus), b.(*VirtualMachineClassStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineCondition)(nil), (*vmoperator.VirtualMachineCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineCondition_To_vmoperator_VirtualMachineCondition(a.(*VirtualMachineCondition), b.(*vmoperator.VirtualMachineCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineCondition)(nil), (*VirtualMachineCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineCondition_To_v1alpha1_VirtualMachineCondition(a.(*vmoperator.VirtualMachineCondition), b.(*VirtualMachineCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineImage)(nil), (*vmoperator.VirtualMachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineImage_To_vmoperator_VirtualMachineImage(a.(*VirtualMachineImage), b.(*vmoperator.VirtualMachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineImage)(nil), (*VirtualMachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineImage_To_v1alpha1_VirtualMachineImage(a.(*vmoperator.VirtualMachineImage), b.(*VirtualMachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineImageList)(nil), (*vmoperator.VirtualMachineImageList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineImageList_To_vmoperator_VirtualMachineImageList(a.(*VirtualMachineImageList), b.(*vmoperator.VirtualMachineImageList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineImageList)(nil), (*VirtualMachineImageList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineImageList_To_v1alpha1_VirtualMachineImageList(a.(*vmoperator.VirtualMachineImageList), b.(*VirtualMachineImageList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineImageSpec)(nil), (*vmoperator.VirtualMachineImageSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineImageSpec_To_vmoperator_VirtualMachineImageSpec(a.(*VirtualMachineImageSpec), b.(*vmoperator.VirtualMachineImageSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineImageSpec)(nil), (*VirtualMachineImageSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineImageSpec_To_v1alpha1_VirtualMachineImageSpec(a.(*vmoperator.VirtualMachineImageSpec), b.(*VirtualMachineImageSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineImageStatus)(nil), (*vmoperator.VirtualMachineImageStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineImageStatus_To_vmoperator_VirtualMachineImageStatus(a.(*VirtualMachineImageStatus), b.(*vmoperator.VirtualMachineImageStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineImageStatus)(nil), (*VirtualMachineImageStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineImageStatus_To_v1alpha1_VirtualMachineImageStatus(a.(*vmoperator.VirtualMachineImageStatus), b.(*VirtualMachineImageStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineList)(nil), (*vmoperator.VirtualMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineList_To_vmoperator_VirtualMachineList(a.(*VirtualMachineList), b.(*vmoperator.VirtualMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineList)(nil), (*VirtualMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineList_To_v1alpha1_VirtualMachineList(a.(*vmoperator.VirtualMachineList), b.(*VirtualMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineMetadata)(nil), (*vmoperator.VirtualMachineMetadata)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineMetadata_To_vmoperator_VirtualMachineMetadata(a.(*VirtualMachineMetadata), b.(*vmoperator.VirtualMachineMetadata), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineMetadata)(nil), (*VirtualMachineMetadata)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineMetadata_To_v1alpha1_VirtualMachineMetadata(a.(*vmoperator.VirtualMachineMetadata), b.(*VirtualMachineMetadata), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineNetworkInterface)(nil), (*vmoperator.VirtualMachineNetworkInterface)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineNetworkInterface_To_vmoperator_VirtualMachineNetworkInterface(a.(*VirtualMachineNetworkInterface), b.(*vmoperator.VirtualMachineNetworkInterface), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineNetworkInterface)(nil), (*VirtualMachineNetworkInterface)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineNetworkInterface_To_v1alpha1_VirtualMachineNetworkInterface(a.(*vmoperator.VirtualMachineNetworkInterface), b.(*VirtualMachineNetworkInterface), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachinePort)(nil), (*vmoperator.VirtualMachinePort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachinePort_To_vmoperator_VirtualMachinePort(a.(*VirtualMachinePort), b.(*vmoperator.VirtualMachinePort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachinePort)(nil), (*VirtualMachinePort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachinePort_To_v1alpha1_VirtualMachinePort(a.(*vmoperator.VirtualMachinePort), b.(*VirtualMachinePort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineService)(nil), (*vmoperator.VirtualMachineService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineService_To_vmoperator_VirtualMachineService(a.(*VirtualMachineService), b.(*vmoperator.VirtualMachineService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineService)(nil), (*VirtualMachineService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineService_To_v1alpha1_VirtualMachineService(a.(*vmoperator.VirtualMachineService), b.(*VirtualMachineService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineServiceList)(nil), (*vmoperator.VirtualMachineServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineServiceList_To_vmoperator_VirtualMachineServiceList(a.(*VirtualMachineServiceList), b.(*vmoperator.VirtualMachineServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineServiceList)(nil), (*VirtualMachineServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineServiceList_To_v1alpha1_VirtualMachineServiceList(a.(*vmoperator.VirtualMachineServiceList), b.(*VirtualMachineServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineServicePort)(nil), (*vmoperator.VirtualMachineServicePort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineServicePort_To_vmoperator_VirtualMachineServicePort(a.(*VirtualMachineServicePort), b.(*vmoperator.VirtualMachineServicePort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineServicePort)(nil), (*VirtualMachineServicePort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineServicePort_To_v1alpha1_VirtualMachineServicePort(a.(*vmoperator.VirtualMachineServicePort), b.(*VirtualMachineServicePort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineServiceSpec)(nil), (*vmoperator.VirtualMachineServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineServiceSpec_To_vmoperator_VirtualMachineServiceSpec(a.(*VirtualMachineServiceSpec), b.(*vmoperator.VirtualMachineServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineServiceSpec)(nil), (*VirtualMachineServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineServiceSpec_To_v1alpha1_VirtualMachineServiceSpec(a.(*vmoperator.VirtualMachineServiceSpec), b.(*VirtualMachineServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineServiceStatus)(nil), (*vmoperator.VirtualMachineServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineServiceStatus_To_vmoperator_VirtualMachineServiceStatus(a.(*VirtualMachineServiceStatus), b.(*vmoperator.VirtualMachineServiceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineServiceStatus)(nil), (*VirtualMachineServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineServiceStatus_To_v1alpha1_VirtualMachineServiceStatus(a.(*vmoperator.VirtualMachineServiceStatus), b.(*VirtualMachineServiceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineSpec)(nil), (*vmoperator.VirtualMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineSpec_To_vmoperator_VirtualMachineSpec(a.(*VirtualMachineSpec), b.(*vmoperator.VirtualMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineSpec)(nil), (*VirtualMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineSpec_To_v1alpha1_VirtualMachineSpec(a.(*vmoperator.VirtualMachineSpec), b.(*VirtualMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineStatus)(nil), (*vmoperator.VirtualMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineStatus_To_vmoperator_VirtualMachineStatus(a.(*VirtualMachineStatus), b.(*vmoperator.VirtualMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vmoperator.VirtualMachineStatus)(nil), (*VirtualMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vmoperator_VirtualMachineStatus_To_v1alpha1_VirtualMachineStatus(a.(*vmoperator.VirtualMachineStatus), b.(*VirtualMachineStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_VirtualMachine_To_vmoperator_VirtualMachine(in *VirtualMachine, out *vmoperator.VirtualMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VirtualMachineSpec_To_vmoperator_VirtualMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VirtualMachineStatus_To_vmoperator_VirtualMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VirtualMachine_To_vmoperator_VirtualMachine is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachine_To_vmoperator_VirtualMachine(in *VirtualMachine, out *vmoperator.VirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachine_To_vmoperator_VirtualMachine(in, out, s)
}

func autoConvert_vmoperator_VirtualMachine_To_v1alpha1_VirtualMachine(in *vmoperator.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_vmoperator_VirtualMachineSpec_To_v1alpha1_VirtualMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_vmoperator_VirtualMachineStatus_To_v1alpha1_VirtualMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_vmoperator_VirtualMachine_To_v1alpha1_VirtualMachine is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachine_To_v1alpha1_VirtualMachine(in *vmoperator.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachine_To_v1alpha1_VirtualMachine(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineClass_To_vmoperator_VirtualMachineClass(in *VirtualMachineClass, out *vmoperator.VirtualMachineClass, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VirtualMachineClassSpec_To_vmoperator_VirtualMachineClassSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VirtualMachineClassStatus_To_vmoperator_VirtualMachineClassStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VirtualMachineClass_To_vmoperator_VirtualMachineClass is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineClass_To_vmoperator_VirtualMachineClass(in *VirtualMachineClass, out *vmoperator.VirtualMachineClass, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineClass_To_vmoperator_VirtualMachineClass(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineClass_To_v1alpha1_VirtualMachineClass(in *vmoperator.VirtualMachineClass, out *VirtualMachineClass, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_vmoperator_VirtualMachineClassSpec_To_v1alpha1_VirtualMachineClassSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_vmoperator_VirtualMachineClassStatus_To_v1alpha1_VirtualMachineClassStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_vmoperator_VirtualMachineClass_To_v1alpha1_VirtualMachineClass is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineClass_To_v1alpha1_VirtualMachineClass(in *vmoperator.VirtualMachineClass, out *VirtualMachineClass, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineClass_To_v1alpha1_VirtualMachineClass(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineClassHardware_To_vmoperator_VirtualMachineClassHardware(in *VirtualMachineClassHardware, out *vmoperator.VirtualMachineClassHardware, s conversion.Scope) error {
	out.Cpus = in.Cpus
	out.Memory = in.Memory
	return nil
}

// Convert_v1alpha1_VirtualMachineClassHardware_To_vmoperator_VirtualMachineClassHardware is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineClassHardware_To_vmoperator_VirtualMachineClassHardware(in *VirtualMachineClassHardware, out *vmoperator.VirtualMachineClassHardware, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineClassHardware_To_vmoperator_VirtualMachineClassHardware(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineClassHardware_To_v1alpha1_VirtualMachineClassHardware(in *vmoperator.VirtualMachineClassHardware, out *VirtualMachineClassHardware, s conversion.Scope) error {
	out.Cpus = in.Cpus
	out.Memory = in.Memory
	return nil
}

// Convert_vmoperator_VirtualMachineClassHardware_To_v1alpha1_VirtualMachineClassHardware is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineClassHardware_To_v1alpha1_VirtualMachineClassHardware(in *vmoperator.VirtualMachineClassHardware, out *VirtualMachineClassHardware, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineClassHardware_To_v1alpha1_VirtualMachineClassHardware(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineClassList_To_vmoperator_VirtualMachineClassList(in *VirtualMachineClassList, out *vmoperator.VirtualMachineClassList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]vmoperator.VirtualMachineClass)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VirtualMachineClassList_To_vmoperator_VirtualMachineClassList is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineClassList_To_vmoperator_VirtualMachineClassList(in *VirtualMachineClassList, out *vmoperator.VirtualMachineClassList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineClassList_To_vmoperator_VirtualMachineClassList(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineClassList_To_v1alpha1_VirtualMachineClassList(in *vmoperator.VirtualMachineClassList, out *VirtualMachineClassList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VirtualMachineClass)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_vmoperator_VirtualMachineClassList_To_v1alpha1_VirtualMachineClassList is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineClassList_To_v1alpha1_VirtualMachineClassList(in *vmoperator.VirtualMachineClassList, out *VirtualMachineClassList, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineClassList_To_v1alpha1_VirtualMachineClassList(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineClassPolicies_To_vmoperator_VirtualMachineClassPolicies(in *VirtualMachineClassPolicies, out *vmoperator.VirtualMachineClassPolicies, s conversion.Scope) error {
	if err := Convert_v1alpha1_VirtualMachineClassResources_To_vmoperator_VirtualMachineClassResources(&in.Resources, &out.Resources, s); err != nil {
		return err
	}
	out.StorageClass = in.StorageClass
	return nil
}

// Convert_v1alpha1_VirtualMachineClassPolicies_To_vmoperator_VirtualMachineClassPolicies is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineClassPolicies_To_vmoperator_VirtualMachineClassPolicies(in *VirtualMachineClassPolicies, out *vmoperator.VirtualMachineClassPolicies, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineClassPolicies_To_vmoperator_VirtualMachineClassPolicies(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineClassPolicies_To_v1alpha1_VirtualMachineClassPolicies(in *vmoperator.VirtualMachineClassPolicies, out *VirtualMachineClassPolicies, s conversion.Scope) error {
	if err := Convert_vmoperator_VirtualMachineClassResources_To_v1alpha1_VirtualMachineClassResources(&in.Resources, &out.Resources, s); err != nil {
		return err
	}
	out.StorageClass = in.StorageClass
	return nil
}

// Convert_vmoperator_VirtualMachineClassPolicies_To_v1alpha1_VirtualMachineClassPolicies is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineClassPolicies_To_v1alpha1_VirtualMachineClassPolicies(in *vmoperator.VirtualMachineClassPolicies, out *VirtualMachineClassPolicies, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineClassPolicies_To_v1alpha1_VirtualMachineClassPolicies(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineClassResourceSpec_To_vmoperator_VirtualMachineClassResourceSpec(in *VirtualMachineClassResourceSpec, out *vmoperator.VirtualMachineClassResourceSpec, s conversion.Scope) error {
	out.Cpu = in.Cpu
	out.Memory = in.Memory
	return nil
}

// Convert_v1alpha1_VirtualMachineClassResourceSpec_To_vmoperator_VirtualMachineClassResourceSpec is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineClassResourceSpec_To_vmoperator_VirtualMachineClassResourceSpec(in *VirtualMachineClassResourceSpec, out *vmoperator.VirtualMachineClassResourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineClassResourceSpec_To_vmoperator_VirtualMachineClassResourceSpec(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineClassResourceSpec_To_v1alpha1_VirtualMachineClassResourceSpec(in *vmoperator.VirtualMachineClassResourceSpec, out *VirtualMachineClassResourceSpec, s conversion.Scope) error {
	out.Cpu = in.Cpu
	out.Memory = in.Memory
	return nil
}

// Convert_vmoperator_VirtualMachineClassResourceSpec_To_v1alpha1_VirtualMachineClassResourceSpec is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineClassResourceSpec_To_v1alpha1_VirtualMachineClassResourceSpec(in *vmoperator.VirtualMachineClassResourceSpec, out *VirtualMachineClassResourceSpec, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineClassResourceSpec_To_v1alpha1_VirtualMachineClassResourceSpec(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineClassResources_To_vmoperator_VirtualMachineClassResources(in *VirtualMachineClassResources, out *vmoperator.VirtualMachineClassResources, s conversion.Scope) error {
	if err := Convert_v1alpha1_VirtualMachineClassResourceSpec_To_vmoperator_VirtualMachineClassResourceSpec(&in.Requests, &out.Requests, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VirtualMachineClassResourceSpec_To_vmoperator_VirtualMachineClassResourceSpec(&in.Limits, &out.Limits, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VirtualMachineClassResources_To_vmoperator_VirtualMachineClassResources is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineClassResources_To_vmoperator_VirtualMachineClassResources(in *VirtualMachineClassResources, out *vmoperator.VirtualMachineClassResources, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineClassResources_To_vmoperator_VirtualMachineClassResources(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineClassResources_To_v1alpha1_VirtualMachineClassResources(in *vmoperator.VirtualMachineClassResources, out *VirtualMachineClassResources, s conversion.Scope) error {
	if err := Convert_vmoperator_VirtualMachineClassResourceSpec_To_v1alpha1_VirtualMachineClassResourceSpec(&in.Requests, &out.Requests, s); err != nil {
		return err
	}
	if err := Convert_vmoperator_VirtualMachineClassResourceSpec_To_v1alpha1_VirtualMachineClassResourceSpec(&in.Limits, &out.Limits, s); err != nil {
		return err
	}
	return nil
}

// Convert_vmoperator_VirtualMachineClassResources_To_v1alpha1_VirtualMachineClassResources is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineClassResources_To_v1alpha1_VirtualMachineClassResources(in *vmoperator.VirtualMachineClassResources, out *VirtualMachineClassResources, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineClassResources_To_v1alpha1_VirtualMachineClassResources(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineClassSpec_To_vmoperator_VirtualMachineClassSpec(in *VirtualMachineClassSpec, out *vmoperator.VirtualMachineClassSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_VirtualMachineClassHardware_To_vmoperator_VirtualMachineClassHardware(&in.Hardware, &out.Hardware, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VirtualMachineClassPolicies_To_vmoperator_VirtualMachineClassPolicies(&in.Policies, &out.Policies, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VirtualMachineClassSpec_To_vmoperator_VirtualMachineClassSpec is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineClassSpec_To_vmoperator_VirtualMachineClassSpec(in *VirtualMachineClassSpec, out *vmoperator.VirtualMachineClassSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineClassSpec_To_vmoperator_VirtualMachineClassSpec(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineClassSpec_To_v1alpha1_VirtualMachineClassSpec(in *vmoperator.VirtualMachineClassSpec, out *VirtualMachineClassSpec, s conversion.Scope) error {
	if err := Convert_vmoperator_VirtualMachineClassHardware_To_v1alpha1_VirtualMachineClassHardware(&in.Hardware, &out.Hardware, s); err != nil {
		return err
	}
	if err := Convert_vmoperator_VirtualMachineClassPolicies_To_v1alpha1_VirtualMachineClassPolicies(&in.Policies, &out.Policies, s); err != nil {
		return err
	}
	return nil
}

// Convert_vmoperator_VirtualMachineClassSpec_To_v1alpha1_VirtualMachineClassSpec is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineClassSpec_To_v1alpha1_VirtualMachineClassSpec(in *vmoperator.VirtualMachineClassSpec, out *VirtualMachineClassSpec, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineClassSpec_To_v1alpha1_VirtualMachineClassSpec(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineClassStatus_To_vmoperator_VirtualMachineClassStatus(in *VirtualMachineClassStatus, out *vmoperator.VirtualMachineClassStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_VirtualMachineClassStatus_To_vmoperator_VirtualMachineClassStatus is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineClassStatus_To_vmoperator_VirtualMachineClassStatus(in *VirtualMachineClassStatus, out *vmoperator.VirtualMachineClassStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineClassStatus_To_vmoperator_VirtualMachineClassStatus(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineClassStatus_To_v1alpha1_VirtualMachineClassStatus(in *vmoperator.VirtualMachineClassStatus, out *VirtualMachineClassStatus, s conversion.Scope) error {
	return nil
}

// Convert_vmoperator_VirtualMachineClassStatus_To_v1alpha1_VirtualMachineClassStatus is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineClassStatus_To_v1alpha1_VirtualMachineClassStatus(in *vmoperator.VirtualMachineClassStatus, out *VirtualMachineClassStatus, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineClassStatus_To_v1alpha1_VirtualMachineClassStatus(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineCondition_To_vmoperator_VirtualMachineCondition(in *VirtualMachineCondition, out *vmoperator.VirtualMachineCondition, s conversion.Scope) error {
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Message = in.Message
	out.Reason = in.Reason
	out.Status = in.Status
	out.Type = in.Type
	return nil
}

// Convert_v1alpha1_VirtualMachineCondition_To_vmoperator_VirtualMachineCondition is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineCondition_To_vmoperator_VirtualMachineCondition(in *VirtualMachineCondition, out *vmoperator.VirtualMachineCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineCondition_To_vmoperator_VirtualMachineCondition(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineCondition_To_v1alpha1_VirtualMachineCondition(in *vmoperator.VirtualMachineCondition, out *VirtualMachineCondition, s conversion.Scope) error {
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Message = in.Message
	out.Reason = in.Reason
	out.Status = in.Status
	out.Type = in.Type
	return nil
}

// Convert_vmoperator_VirtualMachineCondition_To_v1alpha1_VirtualMachineCondition is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineCondition_To_v1alpha1_VirtualMachineCondition(in *vmoperator.VirtualMachineCondition, out *VirtualMachineCondition, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineCondition_To_v1alpha1_VirtualMachineCondition(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineImage_To_vmoperator_VirtualMachineImage(in *VirtualMachineImage, out *vmoperator.VirtualMachineImage, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VirtualMachineImageSpec_To_vmoperator_VirtualMachineImageSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VirtualMachineImageStatus_To_vmoperator_VirtualMachineImageStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VirtualMachineImage_To_vmoperator_VirtualMachineImage is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineImage_To_vmoperator_VirtualMachineImage(in *VirtualMachineImage, out *vmoperator.VirtualMachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineImage_To_vmoperator_VirtualMachineImage(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineImage_To_v1alpha1_VirtualMachineImage(in *vmoperator.VirtualMachineImage, out *VirtualMachineImage, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_vmoperator_VirtualMachineImageSpec_To_v1alpha1_VirtualMachineImageSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_vmoperator_VirtualMachineImageStatus_To_v1alpha1_VirtualMachineImageStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_vmoperator_VirtualMachineImage_To_v1alpha1_VirtualMachineImage is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineImage_To_v1alpha1_VirtualMachineImage(in *vmoperator.VirtualMachineImage, out *VirtualMachineImage, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineImage_To_v1alpha1_VirtualMachineImage(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineImageList_To_vmoperator_VirtualMachineImageList(in *VirtualMachineImageList, out *vmoperator.VirtualMachineImageList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]vmoperator.VirtualMachineImage)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VirtualMachineImageList_To_vmoperator_VirtualMachineImageList is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineImageList_To_vmoperator_VirtualMachineImageList(in *VirtualMachineImageList, out *vmoperator.VirtualMachineImageList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineImageList_To_vmoperator_VirtualMachineImageList(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineImageList_To_v1alpha1_VirtualMachineImageList(in *vmoperator.VirtualMachineImageList, out *VirtualMachineImageList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VirtualMachineImage)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_vmoperator_VirtualMachineImageList_To_v1alpha1_VirtualMachineImageList is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineImageList_To_v1alpha1_VirtualMachineImageList(in *vmoperator.VirtualMachineImageList, out *VirtualMachineImageList, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineImageList_To_v1alpha1_VirtualMachineImageList(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineImageSpec_To_vmoperator_VirtualMachineImageSpec(in *VirtualMachineImageSpec, out *vmoperator.VirtualMachineImageSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.ImageSource = in.ImageSource
	out.ImageSourceType = in.ImageSourceType
	out.ImagePath = in.ImagePath
	return nil
}

// Convert_v1alpha1_VirtualMachineImageSpec_To_vmoperator_VirtualMachineImageSpec is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineImageSpec_To_vmoperator_VirtualMachineImageSpec(in *VirtualMachineImageSpec, out *vmoperator.VirtualMachineImageSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineImageSpec_To_vmoperator_VirtualMachineImageSpec(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineImageSpec_To_v1alpha1_VirtualMachineImageSpec(in *vmoperator.VirtualMachineImageSpec, out *VirtualMachineImageSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.ImageSource = in.ImageSource
	out.ImageSourceType = in.ImageSourceType
	out.ImagePath = in.ImagePath
	return nil
}

// Convert_vmoperator_VirtualMachineImageSpec_To_v1alpha1_VirtualMachineImageSpec is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineImageSpec_To_v1alpha1_VirtualMachineImageSpec(in *vmoperator.VirtualMachineImageSpec, out *VirtualMachineImageSpec, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineImageSpec_To_v1alpha1_VirtualMachineImageSpec(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineImageStatus_To_vmoperator_VirtualMachineImageStatus(in *VirtualMachineImageStatus, out *vmoperator.VirtualMachineImageStatus, s conversion.Scope) error {
	out.Uuid = in.Uuid
	out.InternalId = in.InternalId
	out.PowerState = in.PowerState
	return nil
}

// Convert_v1alpha1_VirtualMachineImageStatus_To_vmoperator_VirtualMachineImageStatus is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineImageStatus_To_vmoperator_VirtualMachineImageStatus(in *VirtualMachineImageStatus, out *vmoperator.VirtualMachineImageStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineImageStatus_To_vmoperator_VirtualMachineImageStatus(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineImageStatus_To_v1alpha1_VirtualMachineImageStatus(in *vmoperator.VirtualMachineImageStatus, out *VirtualMachineImageStatus, s conversion.Scope) error {
	out.Uuid = in.Uuid
	out.InternalId = in.InternalId
	out.PowerState = in.PowerState
	return nil
}

// Convert_vmoperator_VirtualMachineImageStatus_To_v1alpha1_VirtualMachineImageStatus is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineImageStatus_To_v1alpha1_VirtualMachineImageStatus(in *vmoperator.VirtualMachineImageStatus, out *VirtualMachineImageStatus, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineImageStatus_To_v1alpha1_VirtualMachineImageStatus(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineList_To_vmoperator_VirtualMachineList(in *VirtualMachineList, out *vmoperator.VirtualMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]vmoperator.VirtualMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VirtualMachineList_To_vmoperator_VirtualMachineList is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineList_To_vmoperator_VirtualMachineList(in *VirtualMachineList, out *vmoperator.VirtualMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineList_To_vmoperator_VirtualMachineList(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineList_To_v1alpha1_VirtualMachineList(in *vmoperator.VirtualMachineList, out *VirtualMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VirtualMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_vmoperator_VirtualMachineList_To_v1alpha1_VirtualMachineList is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineList_To_v1alpha1_VirtualMachineList(in *vmoperator.VirtualMachineList, out *VirtualMachineList, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineList_To_v1alpha1_VirtualMachineList(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineMetadata_To_vmoperator_VirtualMachineMetadata(in *VirtualMachineMetadata, out *vmoperator.VirtualMachineMetadata, s conversion.Scope) error {
	out.ConfigMapName = in.ConfigMapName
	out.Transport = in.Transport
	return nil
}

// Convert_v1alpha1_VirtualMachineMetadata_To_vmoperator_VirtualMachineMetadata is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineMetadata_To_vmoperator_VirtualMachineMetadata(in *VirtualMachineMetadata, out *vmoperator.VirtualMachineMetadata, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineMetadata_To_vmoperator_VirtualMachineMetadata(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineMetadata_To_v1alpha1_VirtualMachineMetadata(in *vmoperator.VirtualMachineMetadata, out *VirtualMachineMetadata, s conversion.Scope) error {
	out.ConfigMapName = in.ConfigMapName
	out.Transport = in.Transport
	return nil
}

// Convert_vmoperator_VirtualMachineMetadata_To_v1alpha1_VirtualMachineMetadata is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineMetadata_To_v1alpha1_VirtualMachineMetadata(in *vmoperator.VirtualMachineMetadata, out *VirtualMachineMetadata, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineMetadata_To_v1alpha1_VirtualMachineMetadata(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineNetworkInterface_To_vmoperator_VirtualMachineNetworkInterface(in *VirtualMachineNetworkInterface, out *vmoperator.VirtualMachineNetworkInterface, s conversion.Scope) error {
	out.NetworkName = in.NetworkName
	out.EthernetCardType = in.EthernetCardType
	return nil
}

// Convert_v1alpha1_VirtualMachineNetworkInterface_To_vmoperator_VirtualMachineNetworkInterface is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineNetworkInterface_To_vmoperator_VirtualMachineNetworkInterface(in *VirtualMachineNetworkInterface, out *vmoperator.VirtualMachineNetworkInterface, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineNetworkInterface_To_vmoperator_VirtualMachineNetworkInterface(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineNetworkInterface_To_v1alpha1_VirtualMachineNetworkInterface(in *vmoperator.VirtualMachineNetworkInterface, out *VirtualMachineNetworkInterface, s conversion.Scope) error {
	out.NetworkName = in.NetworkName
	out.EthernetCardType = in.EthernetCardType
	return nil
}

// Convert_vmoperator_VirtualMachineNetworkInterface_To_v1alpha1_VirtualMachineNetworkInterface is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineNetworkInterface_To_v1alpha1_VirtualMachineNetworkInterface(in *vmoperator.VirtualMachineNetworkInterface, out *VirtualMachineNetworkInterface, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineNetworkInterface_To_v1alpha1_VirtualMachineNetworkInterface(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachinePort_To_vmoperator_VirtualMachinePort(in *VirtualMachinePort, out *vmoperator.VirtualMachinePort, s conversion.Scope) error {
	out.Port = in.Port
	out.Ip = in.Ip
	out.Name = in.Name
	out.Protocol = v1.Protocol(in.Protocol)
	return nil
}

// Convert_v1alpha1_VirtualMachinePort_To_vmoperator_VirtualMachinePort is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachinePort_To_vmoperator_VirtualMachinePort(in *VirtualMachinePort, out *vmoperator.VirtualMachinePort, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachinePort_To_vmoperator_VirtualMachinePort(in, out, s)
}

func autoConvert_vmoperator_VirtualMachinePort_To_v1alpha1_VirtualMachinePort(in *vmoperator.VirtualMachinePort, out *VirtualMachinePort, s conversion.Scope) error {
	out.Port = in.Port
	out.Ip = in.Ip
	out.Name = in.Name
	out.Protocol = v1.Protocol(in.Protocol)
	return nil
}

// Convert_vmoperator_VirtualMachinePort_To_v1alpha1_VirtualMachinePort is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachinePort_To_v1alpha1_VirtualMachinePort(in *vmoperator.VirtualMachinePort, out *VirtualMachinePort, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachinePort_To_v1alpha1_VirtualMachinePort(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineService_To_vmoperator_VirtualMachineService(in *VirtualMachineService, out *vmoperator.VirtualMachineService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VirtualMachineServiceSpec_To_vmoperator_VirtualMachineServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VirtualMachineServiceStatus_To_vmoperator_VirtualMachineServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VirtualMachineService_To_vmoperator_VirtualMachineService is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineService_To_vmoperator_VirtualMachineService(in *VirtualMachineService, out *vmoperator.VirtualMachineService, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineService_To_vmoperator_VirtualMachineService(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineService_To_v1alpha1_VirtualMachineService(in *vmoperator.VirtualMachineService, out *VirtualMachineService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_vmoperator_VirtualMachineServiceSpec_To_v1alpha1_VirtualMachineServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_vmoperator_VirtualMachineServiceStatus_To_v1alpha1_VirtualMachineServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_vmoperator_VirtualMachineService_To_v1alpha1_VirtualMachineService is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineService_To_v1alpha1_VirtualMachineService(in *vmoperator.VirtualMachineService, out *VirtualMachineService, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineService_To_v1alpha1_VirtualMachineService(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineServiceList_To_vmoperator_VirtualMachineServiceList(in *VirtualMachineServiceList, out *vmoperator.VirtualMachineServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]vmoperator.VirtualMachineService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VirtualMachineServiceList_To_vmoperator_VirtualMachineServiceList is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineServiceList_To_vmoperator_VirtualMachineServiceList(in *VirtualMachineServiceList, out *vmoperator.VirtualMachineServiceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineServiceList_To_vmoperator_VirtualMachineServiceList(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineServiceList_To_v1alpha1_VirtualMachineServiceList(in *vmoperator.VirtualMachineServiceList, out *VirtualMachineServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VirtualMachineService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_vmoperator_VirtualMachineServiceList_To_v1alpha1_VirtualMachineServiceList is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineServiceList_To_v1alpha1_VirtualMachineServiceList(in *vmoperator.VirtualMachineServiceList, out *VirtualMachineServiceList, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineServiceList_To_v1alpha1_VirtualMachineServiceList(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineServicePort_To_vmoperator_VirtualMachineServicePort(in *VirtualMachineServicePort, out *vmoperator.VirtualMachineServicePort, s conversion.Scope) error {
	out.Name = in.Name
	out.Protocol = in.Protocol
	out.Port = in.Port
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_v1alpha1_VirtualMachineServicePort_To_vmoperator_VirtualMachineServicePort is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineServicePort_To_vmoperator_VirtualMachineServicePort(in *VirtualMachineServicePort, out *vmoperator.VirtualMachineServicePort, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineServicePort_To_vmoperator_VirtualMachineServicePort(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineServicePort_To_v1alpha1_VirtualMachineServicePort(in *vmoperator.VirtualMachineServicePort, out *VirtualMachineServicePort, s conversion.Scope) error {
	out.Name = in.Name
	out.Protocol = in.Protocol
	out.Port = in.Port
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_vmoperator_VirtualMachineServicePort_To_v1alpha1_VirtualMachineServicePort is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineServicePort_To_v1alpha1_VirtualMachineServicePort(in *vmoperator.VirtualMachineServicePort, out *VirtualMachineServicePort, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineServicePort_To_v1alpha1_VirtualMachineServicePort(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineServiceSpec_To_vmoperator_VirtualMachineServiceSpec(in *VirtualMachineServiceSpec, out *vmoperator.VirtualMachineServiceSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.Ports = *(*[]vmoperator.VirtualMachineServicePort)(unsafe.Pointer(&in.Ports))
	out.Selector = *(*map[string]string)(unsafe.Pointer(&in.Selector))
	out.ClusterIP = in.ClusterIP
	out.ExternalName = in.ExternalName
	return nil
}

// Convert_v1alpha1_VirtualMachineServiceSpec_To_vmoperator_VirtualMachineServiceSpec is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineServiceSpec_To_vmoperator_VirtualMachineServiceSpec(in *VirtualMachineServiceSpec, out *vmoperator.VirtualMachineServiceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineServiceSpec_To_vmoperator_VirtualMachineServiceSpec(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineServiceSpec_To_v1alpha1_VirtualMachineServiceSpec(in *vmoperator.VirtualMachineServiceSpec, out *VirtualMachineServiceSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.Ports = *(*[]VirtualMachineServicePort)(unsafe.Pointer(&in.Ports))
	out.Selector = *(*map[string]string)(unsafe.Pointer(&in.Selector))
	out.ClusterIP = in.ClusterIP
	out.ExternalName = in.ExternalName
	return nil
}

// Convert_vmoperator_VirtualMachineServiceSpec_To_v1alpha1_VirtualMachineServiceSpec is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineServiceSpec_To_v1alpha1_VirtualMachineServiceSpec(in *vmoperator.VirtualMachineServiceSpec, out *VirtualMachineServiceSpec, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineServiceSpec_To_v1alpha1_VirtualMachineServiceSpec(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineServiceStatus_To_vmoperator_VirtualMachineServiceStatus(in *VirtualMachineServiceStatus, out *vmoperator.VirtualMachineServiceStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_VirtualMachineServiceStatus_To_vmoperator_VirtualMachineServiceStatus is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineServiceStatus_To_vmoperator_VirtualMachineServiceStatus(in *VirtualMachineServiceStatus, out *vmoperator.VirtualMachineServiceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineServiceStatus_To_vmoperator_VirtualMachineServiceStatus(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineServiceStatus_To_v1alpha1_VirtualMachineServiceStatus(in *vmoperator.VirtualMachineServiceStatus, out *VirtualMachineServiceStatus, s conversion.Scope) error {
	return nil
}

// Convert_vmoperator_VirtualMachineServiceStatus_To_v1alpha1_VirtualMachineServiceStatus is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineServiceStatus_To_v1alpha1_VirtualMachineServiceStatus(in *vmoperator.VirtualMachineServiceStatus, out *VirtualMachineServiceStatus, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineServiceStatus_To_v1alpha1_VirtualMachineServiceStatus(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineSpec_To_vmoperator_VirtualMachineSpec(in *VirtualMachineSpec, out *vmoperator.VirtualMachineSpec, s conversion.Scope) error {
	out.ImageName = in.ImageName
	out.ClassName = in.ClassName
	out.PowerState = in.PowerState
	out.Env = in.Env
	out.Ports = *(*[]vmoperator.VirtualMachinePort)(unsafe.Pointer(&in.Ports))
	out.VmMetadata = (*vmoperator.VirtualMachineMetadata)(unsafe.Pointer(in.VmMetadata))
	out.NetworkInterfaces = *(*[]vmoperator.VirtualMachineNetworkInterface)(unsafe.Pointer(&in.NetworkInterfaces))
	out.StorageClass = in.StorageClass
	return nil
}

// Convert_v1alpha1_VirtualMachineSpec_To_vmoperator_VirtualMachineSpec is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineSpec_To_vmoperator_VirtualMachineSpec(in *VirtualMachineSpec, out *vmoperator.VirtualMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineSpec_To_vmoperator_VirtualMachineSpec(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineSpec_To_v1alpha1_VirtualMachineSpec(in *vmoperator.VirtualMachineSpec, out *VirtualMachineSpec, s conversion.Scope) error {
	out.ImageName = in.ImageName
	out.ClassName = in.ClassName
	out.PowerState = in.PowerState
	out.Env = in.Env
	out.Ports = *(*[]VirtualMachinePort)(unsafe.Pointer(&in.Ports))
	out.VmMetadata = (*VirtualMachineMetadata)(unsafe.Pointer(in.VmMetadata))
	out.NetworkInterfaces = *(*[]VirtualMachineNetworkInterface)(unsafe.Pointer(&in.NetworkInterfaces))
	out.StorageClass = in.StorageClass
	return nil
}

// Convert_vmoperator_VirtualMachineSpec_To_v1alpha1_VirtualMachineSpec is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineSpec_To_v1alpha1_VirtualMachineSpec(in *vmoperator.VirtualMachineSpec, out *VirtualMachineSpec, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineSpec_To_v1alpha1_VirtualMachineSpec(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineStatus_To_vmoperator_VirtualMachineStatus(in *VirtualMachineStatus, out *vmoperator.VirtualMachineStatus, s conversion.Scope) error {
	out.Conditions = *(*[]vmoperator.VirtualMachineCondition)(unsafe.Pointer(&in.Conditions))
	out.Host = in.Host
	out.PowerState = in.PowerState
	out.Phase = vmoperator.VMStatusPhase(in.Phase)
	out.VmIp = in.VmIp
	return nil
}

// Convert_v1alpha1_VirtualMachineStatus_To_vmoperator_VirtualMachineStatus is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineStatus_To_vmoperator_VirtualMachineStatus(in *VirtualMachineStatus, out *vmoperator.VirtualMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineStatus_To_vmoperator_VirtualMachineStatus(in, out, s)
}

func autoConvert_vmoperator_VirtualMachineStatus_To_v1alpha1_VirtualMachineStatus(in *vmoperator.VirtualMachineStatus, out *VirtualMachineStatus, s conversion.Scope) error {
	out.Conditions = *(*[]VirtualMachineCondition)(unsafe.Pointer(&in.Conditions))
	out.Host = in.Host
	out.PowerState = in.PowerState
	out.Phase = VMStatusPhase(in.Phase)
	out.VmIp = in.VmIp
	return nil
}

// Convert_vmoperator_VirtualMachineStatus_To_v1alpha1_VirtualMachineStatus is an autogenerated conversion function.
func Convert_vmoperator_VirtualMachineStatus_To_v1alpha1_VirtualMachineStatus(in *vmoperator.VirtualMachineStatus, out *VirtualMachineStatus, s conversion.Scope) error {
	return autoConvert_vmoperator_VirtualMachineStatus_To_v1alpha1_VirtualMachineStatus(in, out, s)
}
