/* **********************************************************
 * Copyright 2018 VMware, Inc.  All rights reserved. -- VMware Confidential
 * **********************************************************/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type VirtualMachineExpansion interface{}

type VirtualMachineImageExpansion interface{}

type VirtualMachineServiceExpansion interface{}
