# Requests denied by this directive will not be served from the cache and their
# responses will not be stored in the cache. This directive has no effect on
# other transactions and on already cached responses. Denies both serving a hit
# and storing a miss.
cache deny all

# Allow all other access to this proxy
http_access allow all

# The socket addresses where Squid will listen for HTTP client requests. You
# may specify multiple socket addresses. There are three forms: port alone,
# hostname with port, and IP address with port. If you specify a hostname or IP
# address, Squid binds the socket to that specific address. Squid normally
# listens to port 3128. 0.0.0.0 is here to force Squid to bind on IPv4.
http_port 0.0.0.0:3128

# With the IPv6 Internet being as fast or faster than IPv4 Internet for most
# networks Squid prefers to contact websites over IPv6. This option reverses
# the order of preference to make Squid contact dual-stack websites over IPv4
# first. Squid will still perform both IPv6 and IPv4 DNS lookups before
# connecting.
dns_v4_first on
