name: pr-reports

on:
  workflow_run:
    workflows:
    - ci
    types:
    - completed

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:

    - name: Fetch pull request reports
      uses: actions/github-script@v7
      id: fetch-pr-reports
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.payload.workflow_run.id,
          });
          let is_pull_request = 'false';
          let matchedArtifacts = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "pull-request-reports"
          });
          if (matchedArtifacts.length > 0) {
            let download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchedArtifacts[0].id,
              archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(
              `${process.env.GITHUB_WORKSPACE}/pull-request-reports.zip`,
              Buffer.from(download.data)
            );
            is_pull_request = 'true';
          }
          core.info('Setting output: is_pull_request=' + is_pull_request);
          core.setOutput('is_pull_request', is_pull_request);

    - name: Unzip pull request reports
      if: steps.fetch-pr-reports.outputs.is_pull_request == 'true'
      run: unzip pull-request-reports.zip

    - name: Load pull request ID
      uses: actions/github-script@v7
      id: load-pull-request-id
      if: steps.fetch-pr-reports.outputs.is_pull_request == 'true'
      with:
        script: |
          let fs = require('fs');
          let pull_request_id = fs.readFileSync(
            `${process.env.GITHUB_WORKSPACE}/pull_request_id`
          );
          core.info('pull_request_id=' + pull_request_id);
          if (pull_request_id == '') {
            core.error('pull_request_id is empty');
          } else {
            core.info('Setting output: pull_request_id=' + pull_request_id);
            core.setOutput('pull_request_id', Number(pull_request_id));
          }

    - name: Update pull request with code coverage
      uses: marocchino/sticky-pull-request-comment@v2
      if: steps.fetch-pr-reports.outputs.is_pull_request == 'true'
      with:
        number: ${{ steps.load-pull-request-id.outputs.pull_request_id }}
        recreate: true
        path: code-coverage-results.md

  test-results:
    runs-on: ubuntu-latest
    steps:

    - name: Fetch pull request reports
      uses: actions/github-script@v7
      id: fetch-pr-reports
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.payload.workflow_run.id,
          });
          let is_pull_request = 'false';
          let matchedArtifacts = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "pull-request-reports"
          });
          if (matchedArtifacts.length > 0) {
            let download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchedArtifacts[0].id,
              archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(
              `${process.env.GITHUB_WORKSPACE}/pull-request-reports.zip`,
              Buffer.from(download.data)
            );
            is_pull_request = 'true';
          }
          core.info('Setting output: is_pull_request=' + is_pull_request);
          core.setOutput('is_pull_request', is_pull_request);

    - name: Unzip pull request reports
      if: steps.fetch-pr-reports.outputs.is_pull_request == 'true'
      run: unzip pull-request-reports.zip

    - name: Update pull request with test report
      uses: mikepenz/action-junit-report@v5
      if: steps.fetch-pr-reports.outputs.is_pull_request == 'true'
      with:
        report_paths: test-report.xml
        commit: ${{ github.event.workflow_run.head_sha }}
        pr_id: ${{ github.event.workflow_run.pull_requests[0].number }}
        comment: true
        updateComment: true
        include_passed: true
        include_time_in_summary: true
