//go:build !ignore_autogenerated

// Copyright (c) 2024 VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package backup

import (
	"k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassicDiskData) DeepCopyInto(out *ClassicDiskData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassicDiskData.
func (in *ClassicDiskData) DeepCopy() *ClassicDiskData {
	if in == nil {
		return nil
	}
	out := new(ClassicDiskData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCDiskData) DeepCopyInto(out *PVCDiskData) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCDiskData.
func (in *PVCDiskData) DeepCopy() *PVCDiskData {
	if in == nil {
		return nil
	}
	out := new(PVCDiskData)
	in.DeepCopyInto(out)
	return out
}
